function k(b,a,c,d){b.v.Eb(b.kb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.we()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.kb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Pb||(b.v.hd(b.Pd),b.Pb=!0)}window.cb=class{constructor(b,a){this.v=b;this.kb=a;this.Pb=!1;this.Pd=()=>this.La()}Zc(){}La(){}};
window.df=class{constructor(){this.Wc=-1}j(){-1!==this.Wc&&(self.clearTimeout(this.Wc),this.Wc=-1)}};"use strict";class aa{constructor(b){this.Dc=b;this.Gc=!1;this.Nc=!0}}function ba(b,a){const c=a.elementId,d=b.cd(c,a),e=new aa(d);b.nb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Nc=!!a.isVisible;d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.Lb&&document.body.appendChild(d)}
function ca(b,a){n(b,"get-element",c=>{const d=w(b,c.elementId);return a(d,c)})}function w(b,a){b=b.nb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Dc}function v(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.he=class extends self.cb{constructor(b){super(b,"sliderbar");this.nb=new Map;this.Lb=!0;t(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.Lb&&c.parentElement.removeChild(c);this.nb.delete(a)}],["set-visible",a=>{if(this.Lb){var c=this.nb.get(a.elementId),d=c.Dc;c.Gc?d.style.display=a.isVisible?"":"none":c.Nc=!!a.isVisible}}],["update-position",a=>{if(this.Lb){var c=this.nb.get(a.elementId),d=c.Dc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Gc||(c.Gc=!0,c.Nc&&(d.style.display=""))}}],["update-state",a=>{const c=w(this,a.elementId);this.rc(c,a)}],["focus",a=>{const c=w(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);
ca(this,a=>a)}cd(){throw Error("required override");}rc(){throw Error("required override");}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ue?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.Ye+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let A=new Audio;
const ka={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const G=[],pa=new Map,qa=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.Ka=class b{constructor(a){this.ca=a.$e;this.va=null;this.ba="";this.Ya=a.Xe;this.Bb={};this.Ra=this.ta=null;this.Nb=[];this.I=this.wa=null;this.Kc=!1;this.wd=0;this.qb=null;this.Xa=-1;this.Pe=()=>this.De();this.Wa=[];this.B=a.Qd;this.Qb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Tb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.ze(c));this.C("runtime","create-job-worker",()=>this.Ae());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.ld(a)):this.ld(a)}j(){this.sc();this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}le(){return da&&"cordova"===this.B}nc(){const a=navigator.userAgent;return da&&ta.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}je(){return y}ed(){return y&&ta.has(this.B)}async ld(a){"macos-wkwebview"===this.B&&this.Ie();if("playable-ad"===this.B){this.qa=
self.c3_base64files;this.Tb={};await this.se();for(let d=0,e=a.$a.length;d<e;++d){var c=a.$a[d];this.Tb.hasOwnProperty(c)?a.$a[d]={Ue:!0,Ye:this.Tb[c]}:this.qa.hasOwnProperty(c)&&(a.$a[d]=URL.createObjectURL(this.qa[c]))}a.fc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.hd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.We?this.ba=a.We:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.bf&&(this.Bb=a.bf);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ce(d));this.qb=new self.me(this);await va(this.qb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.ye(a,c.port2):await this.xe(a,c.port2)}uc(a){a=this.Bb.hasOwnProperty(a)?this.Bb[a]:a.endsWith("/workermain.js")&&this.Bb.hasOwnProperty("workermain.js")?this.Bb["workermain.js"]:"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ic(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Qb)return a=await this.Cb(d.Te?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}kd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.gb(),m=a.hf,p=window.cr_previewImageBlobs||this.qa,q=window.cr_previewProjectFileBlobs,B=window.cr_previewProjectFiles,x=window.ff||
"";a=a.Qd;var r=(new URLSearchParams(self.location.search)).has("debug"),C=this.qb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:B,swClientId:x,exportType:a,isDebug:r,ife:!!self.gf,jobScheduler:{inputPort:C.Jc,outputPort:C.Rc,maxNumWorkers:C.Me},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Ya+"opus.wasm.wasm",isFileProtocol:this.Qb,isiOSCordova:this.le(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ye(a,c){const d=this.uc(a.af);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ta.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ta.addEventListener("message",p);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.ic(d,this.ba,{type:"module",name:"Runtime",Te:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.fc||[],g=a.$a;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.B)for(let h=0,m=a.ec.length;h<m;++h){const p=
a.ec[h],q=p[0];if(q===a.Xc||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Ma(q)}this.ta.postMessage(Object.assign(this.kd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ec,mainProjectScript:a.Xc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...wa(this.qb)]);this.Nb=G.map(h=>new h(this));this.jd();xa(this.wa);self.c3_callFunction=(h,m)=>{var p=this.wa;return p.v.gd(p.kb,"js-invoke-function",
{name:h,params:m})};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async xe(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Nb=G.map(g=>new g(this));this.jd();var d=a.$a.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.fc)){var e=[...a.fc].map(g=>g instanceof Blob?URL.createObjectURL(g):
g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;e=a.Xc;const f=a.ec;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await z(h),"preview"!==this.B||d[g]||this.nd(g,"main script did not run to completion")}catch(m){this.nd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await z(h);"preview"===this.B&&"object"!==typeof self.cf.ef?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:sa}),xa(this.wa),this.md(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}nd(a,c){this.Ib();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}md(){this.Ib()}Ib(){const a=
window.Re;a&&(a.parentElement.removeChild(a),window.Re=null)}async Ae(){const a=await ya(this.qb);return{outputPort:a,transferables:[a]}}we(){if(this.ca)throw Error("not available in worker mode");return this.Ra}Eb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}gd(a,c,d,e,f){const g=ra++,h=new Promise((m,p)=>{qa.set(g,{resolve:m,reject:p})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Be(a);if("result"===c)this.Ee(a);else if("runtime-ready"===c)this.Fe();else if("alert-error"===c)this.Ib(),alert(a.message);else if("creating-runtime"===c)this.md();else throw Error(`unknown message '${c}'`);}Be(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=pa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Hb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Hb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Hb(f,!1,""+h)}):this.Hb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Hb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ee(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}C(a,
c,d){let e=pa.get(a);e||(e=new Map,pa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ab(a){if(G.includes(a))throw Error("DOM handler already added");G.push(a)}jd(){for(const a of this.Nb)if("runtime"===a.kb){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Ce(a){this.Eb("debugger","message",a)}Fe(){for(const a of this.Nb)a.Zc()}static gb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ua)}static od(a){ua=!!a}hd(a){this.Wa.push(a);this.zc()}He(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Wa.splice(a,1);this.Wa.length||this.sc()}zc(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Pe))}sc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}De(){this.Xa=-1;for(const a of this.Wa)a();this.zc()}Ba(a){this.wa.Ba(a)}Ja(a){this.wa.Ja(a)}yc(){this.wa.yc()}Gb(a){this.wa.Gb(a)}ke(){return!!ka["audio/webm; codecs=opus"]}async Je(a){a=await this.gd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}oe(a){this.Kc=!0;this.wd=a}ie(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fd(a){return!this.ie(a)}async Ma(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Qb&&this.fd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Cb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ze(a){const c=a.filename;switch(a.as){case "text":return await this.ge(c);
case "buffer":return await this.Cb(c);default:throw Error("unsupported type");}}bd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ge(a){a=await this.bd(a);return await la(a)}tc(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.te(a.filename,a.Ze,a.Se)}}Cb(a){return new Promise((c,d)=>{D.push({filename:a,Ze:e=>{E--;this.tc();c(e)},Se:e=>{E--;this.tc();d(e)}});this.tc()})}async te(a,c,d){try{const e=
await this.bd(a),f=await ma(e);c(f)}catch(e){d(e)}}Ie(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async se(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.re(c,d));await Promise.all(a)}async re(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),
this.Tb[a]=c.str;else{let d=await this.ve(c);d||(d=this.ue(c));this.qa[a]=d}}async ve(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}ue(a){a=this.Ge(a);return this.qe(a.data,a.Ve)}Ge(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ve:a,data:d}}qe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.Ka;
function za(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};
function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}
function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function xa(b){b.vd=!0;b.Oc=b.v.oa();b.rb=b.v.ha()}async function Na(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Oa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Pa(b){return await self.C3_GetSvgImageSize(b.blob)}function Qa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ra(b){self.setTimeout(()=>{b.ud=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Sa(b,!0)),document.addEventListener("resume",()=>Sa(b,!1))):document.addEventListener("visibilitychange",()=>Sa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ma)}}
function Ta(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ua(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Va(b){await Da(b.url)}
function Wa(b,a){b.xd=a.message;-1===b.Ec&&(b.Ec=setTimeout(()=>{b.Ec=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.xd)},250))}function L(b){if(!b.$){var a=H.gb();a&&"any"!==b.Uc&&Xa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.gb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Sa(b,a){a?b.v.sc():b.v.zc();k(b,"visibilitychange",{hidden:a})}function Za(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=Aa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function $a(b,a,c,d){b.$||za(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function ab(b){window!==window.top&&window.focus();db(b.target)&&document.activeElement&&!db(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.wb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),$a(b,d,c,Ba),b.wb=c.buttons)}}
function eb(b,a,c){if(!b.$&&!za(c)){var d=b.wb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.wb=c.buttons;$a(b,c.type,c,Ba)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function fb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function gb(b,a,c,d){const e=b.oa(),f=b.ha();b.Za=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.gb()}):10>d&&hb(b,e,f,d+1)}
function hb(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>gb(b,a,c,d),48)}
function Xa(b){b=b.Uc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function db(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.ab(class extends self.cb{constructor(b){super(b,"runtime");this.Cd=!0;this.vd=!1;this.Za=-1;this.Uc="any";this.pd=this.qd=!1;this.bc=document.createElement("div");this.bc.className="c3-screen-reader-text";this.bc.setAttribute("aria-live","polite");document.body.appendChild(this.bc);this.Ea=null;this.$=!1;this.xd="";this.Ec=-1;this.ud=!1;this.Oc=b.oa();this.rb=b.ha();this.da=this.Ab=0;b.C("canvas","update-size",d=>{var e=this.v;e.Kc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Cd&&(e.style.display="",this.Cd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Na(d));b.C("runtime","raster-svg-image",d=>Oa(d));b.C("runtime","get-svg-image-size",
d=>Pa(d));b.C("runtime","set-target-orientation",d=>{this.Uc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Qa(d));b.C("runtime","go-to-script",d=>Qa(d));b.C("runtime","before-start-ticking",()=>Ra(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ta(this));b.C("runtime","enable-device-motion",()=>Ua(this));b.C("runtime","add-stylesheet",d=>Va(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.bc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.I.style.display="";this.v.oe(d.duration)});b.C("runtime","export-to-video-progress",d=>Wa(this,d));b.C("runtime","exported-to-video",d=>{window.Qe({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Qe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ha(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",
K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.wb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.vd){var d=this.oa();var e=this.ha();if(this.v.ed()){if(this.ud){if(this.Oc===
d&&e<this.rb){this.Ab=this.rb-e;fb(this,this.rb,this.Ab);d=void 0;break a}0<this.Ab&&(this.Ab=0,fb(this,e,this.Ab))}this.Oc=d;this.rb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.gb()});this.v.nc()&&(-1!==this.Za&&clearTimeout(this.Za),gb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Ya(this,d));window.addEventListener("webkitfullscreenerror",d=>Ya(this,d));window.addEventListener("mozfullscreenerror",d=>Ya(this,d));if(b.nc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ha(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.od(!0),L(this)):"exited-fullscreen"===d?(H.od(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Sa=new Set;this.Vb=new WeakSet;this.ua=!1}Zc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},Ca);this.wb=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&k(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("dblclick",a=>$a(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{ab(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);eb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>eb(this,"pointermove",a)),window.addEventListener("mouseup",a=>eb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.yc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.je()&&!this.v.ed()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{fb(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ha(){return this.v.ha()}yc(){var b=
[...this.Sa];this.Sa.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Vb.has(a)||this.Sa.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");this.Vb.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.Vb.has(b)||this.Sa.add(b)})}Ja(b){this.Sa.delete(b);this.Vb.add(b)}Gb(b){this.ua=!!b}});"use strict";
async function va(b){if(b.Ke)throw Error("already initialised");b.Ke=!0;var a=b.xa.uc(("playable-ad"===b.xa.B?b.xa.Ya:"")+"dispatchworker.js");b.Cc=await b.xa.ic(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Jc=a.port1;b.Cc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Rc=await ya(b)}function wa(b){return[b.Jc,b.Rc]}
async function ya(b){const a=b.Dd.length;var c=b.xa.uc(("playable-ad"===b.xa.B?b.xa.Ya:"")+"jobworker.js");c=await b.xa.ic(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Cc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Dd.push(c);return e.port1}
self.me=class{constructor(b){this.xa=b;this.jb=b.ba;this.jb="preview"===b.B?this.jb+"workers/":this.jb+b.Ya;this.Me=Math.min(navigator.hardwareConcurrency||2,16);this.Cc=null;this.Dd=[];this.Rc=this.Jc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ka({$e:!0,af:"workermain.js",$a:["scripts/c3runtime.js"],ec:[],Xc:"",Xe:"scripts/",fc:[],Qd:"html5"}));"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.Yb=!0;b.Vc=a.timeScaleMode;b.Id=["equalpower","HRTF","soundfield"][a.panningModel];b.td=["linear","inverse","exponential"][a.distanceModel];b.Jd=a.refDistance;b.Hd=a.maxDistance;b.Ld=a.rolloffFactor;if(b.v.Kc)b.Yb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.wd)});else{var c={latencyHint:a.latencyHint};b.Od||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,B=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Ed=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(q){P(b.R,!0);var r=b.R,C=q.innerAngle,na=q.outerAngle,oa=q.outerGain;if(r.pb){ob(r,q.x,q.y,q.z,q.angle);var F=self.bb.pe;r.ra[0]!==F(C)&&
(r.ra[0]=F(C),r.F.coneInnerAngle=F(C));r.ra[1]!==F(na)&&(r.ra[1]=F(na),r.F.coneOuterAngle=F(na));r.ra[2]!==oa&&(r.ra[2]=oa,r.F.coneOuterGain=oa)}q.hasOwnProperty("uid")&&(b.R.pa=q.uid)}else"number"===typeof B&&0!==B?(Q(b.R,!0),pb(b.R,B)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,m,p,x)}catch(Bb){console.error("[Construct] Audio: error starting playback: ",Bb);return}finally{c=g.join(" ");d=b.yb.get(c);if(!d)throw Error("expected pending tag");d.Yc--;0===d.Yc&&(d.resolve(),b.yb.delete(c))}u(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of R(b,c))if(!h.Qa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ha=d;h.Pa=g;h.Nd=a}S(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of R(b,c))d.la!==a&&(d.la=a,d.Ca())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of R(b,c))d.oc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.Wd(b,...e);else if("delay"===c)d=new self.Ud(b,...e);else if("convolution"===c){var g=d=new self.Td(b,f.ia,...e),h=a.bufferType;g.rd=a.bufferOriginalUrl;g.sd=h}else if("flanger"===c)d=new self.Xd(b,...e);else if("phaser"===
c)d=new self.Zd(b,...e);else if("gain"===c)d=new self.Yd(b,...e);else if("stereopan"===c)d=new self.ae(b,...e);else if("tremolo"===c)d=new self.be(b,...e);else if("ringmod"===c)d=new self.$d(b,...e);else if("distortion"===c)d=new self.Vd(b,...e);else if("compressor"===c)d=new self.Sd(b,...e);else if("analyser"===c)d=new self.Rd(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.ka.get(h);p||(p=[],g.ka.set(h,p));d.Bd=p.length;d.Tc=h;p.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.cc=a.timeScale;b.Fc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.ua=a.isSilent;b.v.Gb(b.ua);b.Ub=a.masterVolume;b.Oa.gain.value=
b.Ub;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));S(b)}
async function Cb(b,a){try{const c=b.g.suspend(a.time);b.Ad?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Eb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Db(d)),b.Ad=!0);await c}catch(c){Db(c)}}
function kb(b){b.Ob||(b.Ic=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Ob=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ja)if(g.fb()===c)return await Eb(g),g;if(f)return null;if(e&&(b.Yb||b.zd)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.za()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Od;e&&f&&(b.zd=!0);c=!e||b.Yb||f?new self.ee(b,a,c,d,e,f):new self.ce(b,a,c,d,e);b.ja.push(c);await Eb(c);b.Gd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Gd.add(a));return c}
function Fb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Gb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function xb(b,a){a=a.toLowerCase();let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.na()):e.U(d[f+1].N())}}for(const f of Hb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Pc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*Hb(b,a){if(a)for(const c of b.H)Fb(0<c.ma.length?c.ma[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ib(b,a,c){return c?b.v.Je(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Jb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.ma;var c=a;for(const e of c){c=!1;for(const f of b)if(Fb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.fb()===c&&(g.hc()||f))return g.ma=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ac?new self.de(a.s,a,e):new self.fe(a.s,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.yb.get(a);if(!c){let d=null;c={Yc:0,promise:new Promise(e=>d=e),resolve:d};b.yb.set(a,c)}c.Yc++}function rb(b,a){return(b=b.yb.get((0===a.length?b.Ed:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Na.size)u(b);else for(const a of b.H)if(!a.J&&!a.O()){u(b);break}}function Kb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.Lc||(b.Lc=!0,Promise.resolve().then(()=>Lb(b)))}
function Lb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.eb());k(b,"fxstate",{fxstate:a});b.Lc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(B){console.error("[Construct] Audio: error loading audio state: ",B);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),pb(b,d));c.Play(m,p,q,0);a.isPlaying||c.hb();c.wc(a)}}}function Db(b){console.error("[Audio] Offline rendering error: ",b)}
self.bb=class extends self.cb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Ob=this.Ic=!1;this.ya=()=>{if(!this.Ic){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ob&&(this.Ic=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Ob=!1)}};this.ja=[];this.H=[];this.R=null;this.Ed=[];this.Gd=new Set;this.Fd=-1;this.yb=new Map;this.Ub=1;this.ua=!1;this.Vc=0;this.cc=1;this.Fc=0;this.Id="HRTF";this.td="inverse";this.Jd=600;this.Hd=1E4;this.Ld=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.zd=this.Yb=!1;this.Od=this.v.ke();this.ka=new Map;this.Na=new Set;this.Ad=this.Lc=!1;this.Pc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Pc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Gb(this,this.Pc))};this.Mb=null;self.C3Audio_GetOutputStream=()=>{this.Mb||(this.Mb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Mb));return this.Mb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.hb():d.Fb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.Ub=a.vol;this.Oa.gain.value=this.Ub}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Mb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Gb(this.ua);for(const c of this.H)c.Jb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.pc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.qc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);xb(this,a)}}],["tick",a=>{this.cc=a.timeScale;this.Fc=a.gameTime;this.Fd=a.tickCount;if(0!==this.Vc)for(var c of this.H)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Cb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}W(){return this.g}na(){return this.Oa}Db(){return this.ua}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}La(){for(var b of this.Na)b.La();
b=this.g.currentTime;for(var a of this.H)a.La(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.eb());k(this,"state",{tickCount:this.Fd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.Tc,index:c.Bd,peak:c.Va,rms:c.Kd,binCount:c.l.frequencyBinCount,freqBins:c.yd}))});0===a.length&&0===this.Na.size&&this.Pb&&(this.v.He(this.Pd),this.Pb=!1)}static pe(b){return b*ib}static dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ne(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Ka.ab(self.bb);"use strict";function Eb(b){b.Sb||(b.Sb=b.vc());return b.Sb}self.$c=class{constructor(b,a,c,d,e){this.s=b;this.Oe=a;this.Ga=c;this.T=d;this.Le=e;this.Ac="";this.Sb=null}j(){this.Sb=this.s=null}vc(){}W(){return this.s.W()}kc(){return this.Oe}fb(){return this.Ga}jc(){return this.T}za(){return this.Le}ga(){}};"use strict";
self.ce=class extends self.$c{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ac="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.sb=this.tb=null;this.M.addEventListener("canplaythrough",()=>!0);this.xb=this.W().createGain();this.vb=null;this.M.addEventListener("canplay",()=>{this.tb&&(this.tb(),this.sb=this.tb=null);!this.vb&&this.M&&(this.vb=this.W().createMediaElementSource(this.M),this.vb.connect(this.xb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.sb&&(this.sb(f),this.sb=this.tb=null)})}j(){Jb(this.s,this);this.xb.disconnect();this.xb=null;this.vb.disconnect();this.vb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}vc(){return new Promise((b,a)=>{this.tb=b;this.sb=a;this.M.src=this.Ga})}V(){return this.M}ga(){return this.M.duration}};"use strict";
async function Nb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.B&&a.fd(b.Ga)&&a.Qb)b.Da=await a.Cb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Ob(b){if(b.ia)return b.ia;b.ia=await Ib(b.s,b.Da,b.Ne);b.Da=null}
self.ee=class extends self.$c{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ac="webaudio";this.ia=this.Da=null;this.Ne=!!f}j(){Jb(this.s,this);this.ia=this.Da=null;super.j()}async vc(){try{await Nb(this),await Ob(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Pb=0;
function P(b,a){a=!!a;b.pb!==a&&(b.pb=a,b.pb?(Q(b,!1),b.F||(b.F=b.W().createPanner(),b.F.panningModel=b.s.Id,b.F.distanceModel=b.s.td,b.F.refDistance=b.s.Jd,b.F.maxDistance=b.s.Hd,b.F.rolloffFactor=b.s.Ld),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function Q(b,a){a=!!a;b.Rb!==a&&(b.Rb=a,b.Rb?(P(b,!1),b.fa=b.W().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function pb(b,a){b.Rb&&b.Sc!==a&&(b.fa.pan.value=a,b.Sc=a)}function T(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Pa=-1;b.G.gain.value=b.lc()}function Mb(b,a){a=!!a;b.Qa!==a&&(b.Qa=a,b.Jb())}
function ob(b,a,c,d,e){if(b.pb){var f=b.Ua,g=b.Ta,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Mc?b.s.Fc:performance.now()/1E3}
self.ad=class{constructor(b,a,c){this.s=b;this.P=a;this.ma=c;this.Kb=Pb++;this.G=this.W().createGain();this.G.connect(this.na());this.F=null;this.pb=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Rb=!1;this.Sc=0;this.J=!0;this.Y=this.sa=this.K=!1;this.Ha=1;this.Qa=!1;this.la=1;b=this.s.Vc;this.Mc=1===b&&!this.za()||2===b;this.Pa=this.pa=-1;this.Nd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}W(){return this.s.W()}na(){return Gb(this.s,0<this.ma.length?this.ma[0]:"")}kc(){return this.P.kc()}fb(){return this.P.fb()}jc(){return this.P.jc()}za(){return this.P.za()}O(){}hc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Ia(){}ga(){return this.P.ga()}Play(){}Aa(){}hb(){}Fb(){}La(b){-1!==this.Pa&&b>=this.Pa&&(this.Pa=-1,this.Nd&&this.Aa(),Kb(this.s,"fade-ended",this.ma,this.Kb))}lc(){const b=this.Ha;return isFinite(b)?b:0}Db(){return this.s.Db()}Jb(){}pc(){}Ca(){}oc(){}qc(){}mc(){}eb(){var b=
this.Kb,a=this.ma,c=this.ga(),d=-1===this.Pa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Qa,resumePosition:this.mc(),pan:f,stereoPan:this.fa?
this.Sc:null}}wc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ca());Mb(this,b.isMuted)}};"use strict";
self.de=class extends self.ad{constructor(b,a,c){super(b,a,c);this.P.xb.connect(this.G);this.P.onended=()=>this.xc()}j(){this.Aa();this.P.xb.disconnect();super.j()}V(){return this.P.V()}xc(){this.J=!0;this.pa=-1;Kb(this.s,"ended",this.ma,this.Kb)}O(){return this.V().ended}hc(){return this.J?!0:this.O()}Ia(){let b=this.V().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.V();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.fb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.J=!1;this.Y=b;this.la=1}Aa(){const b=this.V();b.paused||b.pause();this.s.Ja(b);this.J=!0;this.K=!1;this.pa=-1}hb(){if(!(this.K||this.J||this.O())){var b=this.V();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Fb(){!this.K||this.J||this.O()||(this.s.Ba(this.V()),this.K=!1)}Jb(){this.V().muted=this.Qa||this.Db()}pc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.V().loop=b)}Ca(){let b=this.la;this.Mc&&(b*=this.s.cc);try{this.V().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}oc(b){if(!this.J&&!this.O())try{this.V().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}mc(){return this.Ia()}qc(b){b?this.IsPlaying()?(this.V().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ba(this.V()),this.sa=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.ib=null}
self.fe=class extends self.ad{constructor(b,a,c){super(b,a,c);this.o=null;this.Wb=d=>this.xc(d);this.Hc=!0;this.ib=null;this.S=this.Xb=this.Zb=0;this.Qc=1}j(){this.Aa();V(this);this.Wb=null;super.j()}xc(b){this.K||this.sa||b.target!==this.ib||(this.J=this.Hc=!0,this.pa=-1,V(this),Kb(this.s,"ended",this.ma,this.Kb))}O(){return!this.J&&this.o&&this.o.loop||this.K?!1:this.Hc}hc(){return!this.o||this.J?!0:this.O()}Ia(){let b;b=this.K?this.S:this.Xb+(U(this)-this.Zb)*this.la;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Qc=1;T(this,a);V(this);this.o=this.W().createBufferSource();this.o.buffer=this.P.ia;this.o.connect(this.G);this.ib=this.o;this.o.onended=this.Wb;this.o.loop=b;this.o.start(d,c);this.K=this.J=this.Hc=!1;this.Y=b;this.la=1;this.Zb=U(this);this.Xb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.J=!0;this.K=!1;this.pa=-1}hb(){this.K||this.J||this.O()||(this.S=this.Ia(),this.Y&&(this.S%=this.ga()),this.K=!0,this.o.stop(0))}Fb(){!this.K||this.J||this.O()||(V(this),this.o=
this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Wb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.Zb=U(this),this.Xb=this.S,this.K=!1)}lc(){return super.lc()*this.Qc}Jb(){this.Qc=this.Qa||this.Db()?0:1;T(this,this.Ha)}pc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ca(){let b=this.la;this.Mc&&(b*=this.s.cc);this.o&&(this.o.playbackRate.value=b)}oc(b){this.J||this.O()||(this.K?this.S=b:(this.hb(),this.S=
b,this.Fb()))}mc(){return this.S}qc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ia(),this.Y&&(this.S%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(V(this),this.o=this.W().createBufferSource(),this.o.buffer=this.P.ia,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Wb,this.o.loop=this.Y,T(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.Zb=U(this),this.Xb=this.S,this.sa=!1)}wc(b){super.wc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.s=b;this.g=b.W();this.Bd=-1;this.T=this.Tc="";this.m=null}j(){this.g=null}N(){}U(){}eb(){return{type:this.T,tag:this.Tc,params:this.m}}}
self.Wd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.Ud=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ub=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.mb=W(this);this.mb.gain.value=c;this.u.connect(this.ub);this.u.connect(this.h);this.ub.connect(this.i);this.ub.connect(this.X);this.X.connect(this.mb);this.mb.connect(this.ub)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.ub.disconnect();
this.X.disconnect();this.mb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){const e=self.bb.dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.Td=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.sd=this.rd="";this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.u.connect(this.lb);this.u.connect(this.h);this.lb.connect(this.i)}j(){this.u.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}eb(){const b=super.eb();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.Xd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.ob=W(this);this.ob.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.ob);this.ob.connect(this.X);this.A.connect(this.L);
this.L.connect(this.X.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.X.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.ob.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.ob.gain,a/100,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.A.frequency,a,c,d)}}};self.Yd=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.bb.dd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ae=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.be=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.$d=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.zb=W(this);this.zb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.zb.gain);this.A.start(0);this.u.connect(this.zb);this.u.connect(this.h);this.zb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.zb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Vd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=W(this);this.ac=W(this);this.$b=W(this);b=d;.01>b&&(b=.01);this.ac.gain.value=b;this.$b.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.dc=this.g.createWaveShaper();this.Bc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Bc[32768+e]=f,this.Bc[32768-
e-1]=-f;this.dc.curve=this.Bc;this.u.connect(this.ac);this.u.connect(this.h);this.ac.connect(this.dc);this.dc.connect(this.$b);this.$b.connect(this.i)}j(){this.u.disconnect();this.ac.disconnect();this.dc.disconnect();this.$b.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Sd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Rd=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.yd=new Float32Array(this.l.frequencyBinCount);this.Md=new Uint8Array(a);this.Kd=this.Va=0;b=this.s;b.Na.add(this);S(b)}j(){this.s.Na.delete(this);this.l.disconnect();super.j()}La(){this.l.getFloatFrequencyData(this.yd);this.l.getByteTimeDomainData(this.Md);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Md[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.bb.ne;this.Va=c(this.Va);this.Kd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Z(b){b.stopPropagation()}
self.Ka.ab(class extends self.he{constructor(b){super(b)}cd(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);c.addEventListener("click",
()=>{var d;d||(d={});d.elementId=b;l(this,"click",d)});c.addEventListener("change",()=>v(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>v(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.rc(c,a);return c}rc(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";
self.Ka.ab(class extends self.cb{constructor(b){super(b,"mouse");t(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";async function Qb(b,a){a=a.type;let c=!0;0===a?c=await Rb():1===a&&(c=await Sb());k(b,"permission-result",{type:a,result:c})}async function Rb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Sb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Ka.ab(class extends self.cb{constructor(b){super(b,"touch");n(this,"request-permission",a=>Qb(this,a))}});
