function m(b,a,c,d){b.s.mb(b.sb,a,c,d)}function n(b,a,c,d){b.s.da?m(b,a,c,d):b.s.Oe()._OnMessageFromDOM({type:"event",component:b.sb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.s.B(b.sb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Vb||(b.s.yc(b.de),b.Vb=!0)}window.gb=class{constructor(b,a){this.s=b;this.sb=a;this.Vb=!1;this.de=()=>this.Oa()}jd(){}Oa(){}};
window.Bf=class{constructor(){this.ed=-1}j(){-1!==this.ed&&(self.clearTimeout(this.ed),this.ed=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Ta.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Tb}
window.nd=class extends self.gb{constructor(b,a){super(b,a);this.Ta=new Map;this.qb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.qb&&d.parentElement.removeChild(d);this.Ta.delete(c)}],["set-visible",c=>{if(this.qb){var d=this.Ta.get(c.elementId),e=d.Tb;d.Nd?e.style.display=c.isVisible?"":"none":d.gf=!!c.isVisible}}],["update-position",c=>{if(this.qb){var d=this.Ta.get(c.elementId),e=d.Tb,f=this.s;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.mf=g;g=f.pd(g);g!==d.Ea&&(e.remove(),f.rc(g).appendChild(e),d.Ea=g,f.Hc());c=c.htmlZIndex;c!==d.Pc&&(d.Pc=c,f.Hc());d.Nd||(d.Nd=!0,d.gf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.rf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.vf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);let la=!1;
window.nb=class b{constructor(a){this.da=a.xf;this.wa=null;this.aa="";this.ab=a.uf;this.Ib={};this.Va=this.ta=null;this.Sa=[];this.ma=null;this.Rd=!0;this.M=[];this.Zc=[];this.$c=!1;this.ee=()=>this.Me();this.Rc=!1;this.Kd=0;this.xb=null;this.$a=-1;this.lf=()=>this.Xe();this.Fb=new Set;this.fd=null;this.fe=[];this.A=a.ge;this.Wb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.da=!1;if("cordova"===this.A&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.Ma()?self.chrome.webview.addEventListener("message",c=>this.zd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.zd(c));this.Zb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.af(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Se());this.B("runtime","cordova-fetch-local-file",c=>this.Te(c));this.B("runtime","create-job-worker",()=>this.Ue());this.B("runtime","send-wrapper-extension-message",c=>this.$e(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.xd(a)):this.xd(a)}j(){this.zc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Va&&(this.Va.j(),this.Va=null);for(const {canvas:a,
eb:c}of this.M)a.remove(),c.remove();this.M.length=0}ye(){return this.M[0].canvas}pd(a){return Math.min(a,this.M.length-1)}rc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].eb}Ce(){return ba&&"cordova"===this.A}kb(){const a=navigator.userAgent;return ba&&ka.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Ae(){return y}qd(){return y&&ka.has(this.A)}sd(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Ma(){return this.sd()||"xbox-uwp-webview2"===this.A}async xd(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.A?this.ob({type:"ready"}):this.Ma()&&(this.cf(),this.fe=(await this.Re()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.Zb={};await this.Je();for(let d=0,e=a.cb.length;d<e;++d){var c=a.cb[d];this.Zb.hasOwnProperty(c)?a.cb[d]={rf:!0,vf:this.Zb[c]}:this.qa.hasOwnProperty(c)&&(a.cb[d]=URL.createObjectURL(this.qa[c]))}a.nc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.yc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.tf?this.aa=a.tf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.zf&&(this.Ib=a.zf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.We(d));this.xb=
new self.De(this);await oa(this.xb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Qe(a,c.port2):await this.Pe(a,c.port2)}Bc(a){a=this.Ib.hasOwnProperty(a)?this.Ib[a]:a.endsWith("/workermain.js")&&this.Ib.hasOwnProperty("workermain.js")?this.Ib["workermain.js"]:"playable-ad"===
this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Wb)return a=await this.Kb(d.qf?a:this.ab+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}wd(a){var c=this.aa,d=location.href,e=this.oa(),f=this.ga(),g=window.devicePixelRatio,h=b.jb(),k=a.Ef,l=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.ge;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.xb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Df,jobScheduler:{inputPort:A.Qc,outputPort:A.Yc,maxNumWorkers:A.hf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ab+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ab+"opus.wasm.wasm",isFileProtocol:this.Wb,isiOSCordova:this.Ce(),isiOSWebView:this.kb(),isWindowsWebView2:this.sd(),isAnyWebView2Wrapper:this.Ma(),wrapperComponentIds:this.fe,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Qe(a,c){const d=this.Bc(a.yf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.pc(d,this.aa,{type:"module",name:"Runtime",qf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,eb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.nc||[],k=a.cb;h=await Promise.all(h.map(l=>this.Pa(l)));k=await Promise.all(k.map(l=>this.Pa(l)));if("cordova"===this.A)for(let l=0,p=a.mc.length;l<p;++l){const r=
a.mc[l],t=r[0];if(t===a.gd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Pa(t)}this.ta.postMessage(Object.assign(this.wd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.mc,mainProjectScript:a.gd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...pa(this.xb)]);this.Sa=F.map(l=>new l(this));this.vd();qa(e);ra(g);sa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.s.td(r.sb,"js-invoke-function",
{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.mb("runtime","go-to-last-error-script"))}async Pe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,eb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Sa=F.map(h=>new h(this));this.vd();qa(d);ra(e);e=a.cb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.nc)){var f=[...a.nc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Pa(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.gd;const g=a.mc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Pa(k),await z(k),"preview"!==this.A||e[h]||this.Bd(h,"main script did not run to completion")}catch(l){this.Bd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Pa(k),await z(k);"preview"===this.A&&"object"!==typeof self.Af.Cf?(this.Pb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.wd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ja}),sa(this.ma),this.yd(),this.Va=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Va,
a))}Bd(a,c){this.Pb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Pb()}Pb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ue(){const a=await ta(this.xb);return{outputPort:a,transferables:[a]}}af(a){if(!this.Rc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,eb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Rd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Rd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,eb:p}=this.M.pop();p.remove();this.da&&!d?this.Zc.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,qa(c),ra(d),this.M.push({canvas:c,eb:d});for(const l of this.Sa)if(l instanceof window.nd&&l.qb)for(const p of l.Ta.values())e=l.s.pd(p.mf),f=p.Ea,-1!==e&&-1!==f&&e!==f&&(f=p.Tb,f.remove(),l.s.rc(e).appendChild(f),p.Ea=e);this.Hc();return{addedCanvases:a,transferables:k}}Se(){for(const a of this.Zc)a.remove();this.Zc.length=0}Hc(){this.$c||(this.$c=!0,this.yc(this.ee))}Me(){this.Ad(this.ee);
this.$c=!1;let a=[];for(var c of this.Sa)if(c instanceof window.nd){var d=c.qb?[...c.Ta.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ea,l=h.Ea;return k!==l?k-l:g.Pc-h.Pc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ea!==c&&(this.ud(c,a.slice(d,e)),c=g.Ea,d=e)}d<e&&this.ud(c,a.slice(d,e))}ud(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Tb);var d=new Set(c);a=this.rc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Oe(){if(this.da)throw Error("not available in worker mode");return this.Va}mb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}td(a,c,d,e,f){const g=ia++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ve(a);if("result"===c)this.Ye(a);else if("runtime-ready"===c)this.Ze();else if("alert-error"===c)this.Pb(),alert(a.message);else if("creating-runtime"===c)this.yd();else throw Error(`unknown message '${c}'`);}Ve(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Ob(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Ob(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Ob(f,!1,""+h)}):this.Ob(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Ob(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ye(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Jb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}vd(){for(const a of this.Sa)if("runtime"===a.sb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}We(a){this.mb("debugger","message",a)}Ze(){for(const a of this.Sa)a.jd()}static jb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||la)}static Cd(a){la=!!a}yc(a){this.Fb.add(a);
this.Gc()}Ad(a){this.Fb.delete(a);0===this.Fb.size&&this.zc()}Gc(){-1===this.$a&&0<this.Fb.size&&(this.$a=requestAnimationFrame(this.lf))}zc(){-1!==this.$a&&(cancelAnimationFrame(this.$a),this.$a=-1)}Xe(){this.$a=-1;for(const a of this.Fb)a();this.Gc()}Ca(a){this.ma.Ca(a)}Na(a){this.ma.Na(a)}Fc(){this.ma.Fc()}Nb(a){this.ma.Nb(a)}Be(){return!!ea["audio/webm; codecs=opus"]}async df(a){a=await this.td("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Fe(a){this.Rc=!0;this.Kd=
a}ze(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}rd(a){return!this.ze(a)}async Pa(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Wb&&this.rd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Te(a){const c=a.filename;switch(a.as){case "text":return await this.xe(c);case "buffer":return await this.Kb(c);default:throw Error("unsupported type");
}}md(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async xe(a){a=await this.md(a);return await fa(a)}Ac(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Ke(a.filename,a.wf,a.pf)}}Kb(a){return new Promise((c,d)=>{D.push({filename:a,wf:e=>{E--;this.Ac();c(e)},pf:e=>{E--;this.Ac();d(e)}});this.Ac()})}async Ke(a,c,d){try{const e=await this.md(a),f=await ha(e);c(f)}catch(e){d(e)}}zd(a){if("entered-fullscreen"===
a)b.Cd(!0),I(this.ma);else if("exited-fullscreen"===a)b.Cd(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.fd(a),this.fd=null):"extension-message"===c?this.mb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}$e(a){this.ob({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}ob(a){this.Ma()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}cf(){window.moveTo=(a,c)=>{this.ob({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.ob({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Re(){return this.Ma()?new Promise(a=>{this.fd=a;this.ob({type:"wrapper-init"})}):Promise.resolve()}async Je(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.Ie(c,d));
await Promise.all(a)}async Ie(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Zb[a]=c.str;else{let d=await this.Ne(c);d||(d=this.Le(c));this.qa[a]=d}}async Ne(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Le(a){a=this.bf(a);return this.He(a.data,
a.sf)}bf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{sf:a,data:d}}He(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.nb,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},wa={dispatchRuntimeEvent:!0};function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);function qa(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function ra(b){b.addEventListener("selectstart",Ea);b.addEventListener("gesturehold",Ea);b.addEventListener("touchstart",Ea)}function sa(b){b.Jd=!0;b.Uc=b.s.oa();b.yb=b.s.ga()}
function I(b){if(!b.ka){var a=J.jb();a&&"any"!==b.cd&&Ha(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ma(b){self.setTimeout(()=>{b.Id=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,"hidden"===document.visibilityState));b.cc=!("hidden"!==document.visibilityState&&!Ga);return{isSuspended:b.cc}}
function Oa(b){b.Ed||(b.Ed=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Pa(b){b.Dd||(b.Dd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Qa(b){await xa(b.url)}
function Ra(b,a){b.Ld=a.message;-1===b.Lc&&(b.Lc=setTimeout(()=>{b.Lc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Ld)},250))}function Sa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.jb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Na(b,a){b.cc!==a&&((b.cc=a)?b.s.zc():b.s.Gc(),m(b,"visibilitychange",{hidden:a}),!a&&b.s.kb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ta(b,a,c){"Backspace"===c.key&&M(c);if(b.s.Ma()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ua.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Wc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Wc=c.buttons)}}function Ua(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Va(b,a,c,d){const e=b.oa(),f=b.ga();b.bb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.jb()}):10>d&&Wa(b,e,f,d+1)}function Wa(b,a,c,d){-1!==b.bb&&clearTimeout(b.bb);b.bb=setTimeout(()=>Va(b,a,c,d),48)}
function Ha(b){b=b.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Jb(class extends self.gb{constructor(b){super(b,"runtime");this.Jd=!1;this.bb=-1;this.cd="any";this.cc=this.Dd=this.Ed=!1;this.jc=document.createElement("div");this.jc.className="c3-screen-reader-text";this.jc.setAttribute("aria-live","polite");document.body.appendChild(this.jc);this.Ga=null;this.ka=!1;this.Ld="";this.Lc=-1;this.Id=!1;this.Uc=b.oa();this.yb=b.ga();this.za=this.Hb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ia(c));b.B("runtime","raster-svg-image",c=>Ja(c));b.B("runtime","get-svg-image-size",c=>Ka(c));b.B("runtime","set-target-orientation",c=>{this.cd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>La(c));b.B("runtime","go-to-script",c=>La(c));b.B("runtime","before-start-ticking",()=>Ma(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Oa(this));b.B("runtime","enable-device-motion",()=>Pa(this));b.B("runtime","add-stylesheet",c=>Qa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.jc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.s.ye().style.display="";this.s.Fe(c.duration)});b.B("runtime","export-to-video-progress",c=>Ra(this,c));b.B("runtime","exported-to-video",c=>{window.nf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.nf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ba(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Wc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Jd){var c=this.oa();var d=this.ga();if(this.s.qd()){if(this.Id){if(this.Uc===
c&&d<this.yb){this.Hb=this.yb-d;Ua(this,this.yb,this.Hb);c=void 0;break a}0<this.Hb&&(this.Hb=0,Ua(this,d,this.Hb))}this.Uc=c;this.yb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.jb()});this.s.kb()&&(-1!==this.bb&&clearTimeout(this.bb),Va(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Sa(this,c));window.addEventListener("webkitfullscreenerror",c=>Sa(this,c));window.addEventListener("mozfullscreenerror",c=>Sa(this,c));if(b.kb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ba(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Wa=new Set;this.ac=new WeakSet;this.va=!1}jd(){window.addEventListener("focus",()=>{m(this,"window-focus",null,wa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},wa);this.Wc=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||Ba(a))&&m(this,"keyboard-blur",null,wa)});window.addEventListener("keydown",a=>Ta(this,"keydown",a));window.addEventListener("keyup",a=>Ta(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,va));window.addEventListener("mousemove",a=>N(this,"mousemove",a,va));window.addEventListener("mouseup",a=>N(this,"mouseup",a,va));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Xa(a.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.s.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.s.Ae()&&!this.s.qd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ua(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.s.kb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.s.oa()}ga(){return this.s.ga()}Fc(){var b=[...this.Wa];this.Wa.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.ac.has(a)||this.Wa.add(a)})}Ca(b){if("function"!==
typeof b.play)throw Error("missing play function");this.ac.delete(b);let a;try{a=b.play()}catch(c){this.Wa.add(b);return}a&&a.catch(()=>{this.ac.has(b)||this.Wa.add(b)})}Na(b){this.Wa.delete(b);this.ac.add(b)}Nb(b){this.va=!!b}});"use strict";
async function oa(b){if(b.ef)throw Error("already initialised");b.ef=!0;var a=b.xa.Bc(("playable-ad"===b.xa.A?b.xa.ab:"")+"dispatchworker.js");b.Kc=await b.xa.pc(a,b.rb,{name:"DispatchWorker"});a=new MessageChannel;b.Qc=a.port1;b.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await ta(b)}function pa(b){return[b.Qc,b.Yc]}
async function ta(b){const a=b.Sd.length;var c=b.xa.Bc(("playable-ad"===b.xa.A?b.xa.ab:"")+"jobworker.js");c=await b.xa.pc(c,b.rb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Sd.push(c);return e.port1}
self.De=class{constructor(b){this.xa=b;this.rb=b.aa;this.rb="preview"===b.A?this.rb+"workers/":this.rb+b.ab;this.hf=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Sd=[];this.Yc=this.Qc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.nb({xf:!0,yf:"workermain.js",cb:["scripts/c3runtime.js"],mc:[],gd:"",uf:"scripts/",nc:[],ge:"html5"}));"use strict";const Ya=180/Math.PI;
async function Za(b,a){if(a.isiOSCordova||a.isSafari)b.ec=!0;b.dd=a.timeScaleMode;b.Xd=["equalpower","HRTF","soundfield"][a.panningModel];b.Hd=["linear","inverse","exponential"][a.distanceModel];b.Yd=a.refDistance;b.Wd=a.maxDistance;b.$d=a.rolloffFactor;if(b.s.Rc)b.ec=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Kd)});else{var c={latencyHint:a.latencyHint};b.ce||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");$a(b);b.g.onstatechange=()=>{"running"!==b.g.state&&$a(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ra=b.g.createGain();b.Ra.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ab(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Td=g.slice(0);bb(b,g);try{b.R=await cb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.wb){db(u,p.x,p.y,p.z,p.angle);var C=self.fb.Ge;u.ra[0]!==C(A)&&
(u.ra[0]=C(A),u.F.coneInnerAngle=C(A));u.ra[1]!==C(ma)&&(u.ra[1]=C(ma),u.F.coneOuterAngle=C(ma));u.ra[2]!==na&&(u.ra[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),eb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(ub){console.error("[Construct] Audio: error starting playback: ",ub);return}finally{c=g.join(" ");d=b.Eb.get(c);if(!d)throw Error("expected pending tag");d.hd--;0===d.hd&&(d.resolve(),b.Eb.delete(c))}w(b)}
async function hb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ib(b,c);for(const h of S(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ua=g;h.be=a}T(b)}async function jb(b,a){const c=a.tags;a=a.rate;await ib(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Da())}async function kb(b,a){const c=a.tags;a=a.pos;await ib(b,c);for(const d of S(b,c))d.vc(a)}
async function lb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await cb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function mb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function ob(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.me(b,...e);else if("delay"===c)d=new self.ke(b,...e);else if("convolution"===c){var g=d=new self.je(b,f.ha,...e),h=a.bufferType;g.Fd=a.bufferOriginalUrl;g.Gd=h}else if("flanger"===c)d=
new self.ne(b,...e);else if("phaser"===c)d=new self.pe(b,...e);else if("gain"===c)d=new self.oe(b,...e);else if("stereopan"===c)d=new self.re(b,...e);else if("tremolo"===c)d=new self.se(b,...e);else if("ringmod"===c)d=new self.qe(b,...e);else if("distortion"===c)d=new self.le(b,...e);else if("compressor"===c)d=new self.ie(b,...e);else if("analyser"===c)d=new self.he(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Qd=l.length;d.bd=
h;l.push(d);pb(g,h)}qb(b)}
async function rb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.kc=a.timeScale;b.Mc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.va=a.isSilent;b.s.Nb(b.va);b.$b=a.masterVolume;b.Ra.gain.value=
b.$b;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>ob(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>sb(b,f,c)));T(b)}
async function tb(b,a){try{const c=b.g.suspend(a.time);b.Pd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.mb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>vb(d)),b.Pd=!0);await c}catch(c){vb(c)}}
function $a(b){b.Ub||(b.Oc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Ub=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.ib()===c)return await wb(g),g;if(f)return null;if(e&&(b.ec||b.Od)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.ce;e&&f&&(b.Od=!0);c=!e||b.ec||f?new self.ve(b,a,c,d,e,f):new self.te(b,a,c,d,e);b.ia.push(c);await wb(c);b.Vd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Vd.add(a));return c}
function xb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function yb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function pb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of zb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Vc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*zb(b,a){if(a)for(const c of b.H)xb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ab(b,a,c){return c?b.s.df(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Bb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(xb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function cb(b,a,c,d,e,f){for(const g of b.H)if(g.ib()===c&&(g.oc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Ic?new self.ue(a.u,a,e):new self.we(a.u,a,e);b.H.push(e);return e}
function bb(b,a){a=a.join(" ");let c=b.Eb.get(a);if(!c){let d=null;c={hd:0,promise:new Promise(e=>d=e),resolve:d};b.Eb.set(a,c)}c.hd++}function ib(b,a){return(b=b.Eb.get((0===a.length?b.Td:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Qa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Cb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function qb(b){b.Sc||(b.Sc=!0,Promise.resolve().then(()=>Db(b)))}
function Db(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.hb());m(b,"fxstate",{fxstate:a});b.Sc=!1}
async function sb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await cb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],f=d.orient,b.Xa[0]=f[0],b.Xa[1]=f[1],b.Xa[2]=f[2],e.setPosition(...b.Ya),e.setOrientation(...b.Xa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),eb(b,d));c.Play(k,l,p,0);a.isPlaying||c.lb();c.Dc(a)}}}function vb(b){console.error("[Audio] Offline rendering error: ",b)}
self.fb=class extends self.gb{constructor(b){super(b,"audio");this.Ra=this.g=null;this.Ub=this.Oc=!1;this.ya=()=>{if(!this.Oc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ub&&(this.Oc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Ub=!1)}};this.ia=[];this.H=[];this.R=null;this.Td=[];this.Vd=new Set;this.Ud=-1;this.Eb=new Map;this.$b=1;this.va=!1;this.dd=0;this.kc=1;this.Mc=0;this.Xd="HRTF";this.Hd="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Od=this.ec=!1;this.ce=this.s.Be();this.ja=new Map;this.Qa=new Set;this.Pd=this.Sc=!1;this.Vc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Vc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(yb(this,this.Vc))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Ra.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>Za(this,a)],["play",a=>ab(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.lb():d.Mb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>hb(this,a)],["set-master-volume",a=>{this.$b=a.vol;this.Ra.gain.value=this.$b}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Eb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.s.Nb(this.va);for(const c of this.H)c.Qb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.wc(a)}],["set-playback-rate",a=>jb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),eb(d,a)}],["seek",a=>kb(this,a)],["preload",a=>lb(this,a)],["unload",a=>mb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.xc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ob(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);qb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);pb(this,a)}}],["tick",a=>{this.kc=a.timeScale;this.Mc=a.gameTime;this.Ud=a.tickCount;if(0!==this.dd)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&db(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>rb(this,a)],["offline-render-audio",a=>tb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ra}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Lb(){return this.va}Ca(b){this.s.Ca(b)}Na(b){this.s.Na(b)}Oa(){for(var b of this.Qa)b.Oa();
b=this.g.currentTime;for(var a of this.H)a.Oa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.hb());m(this,"state",{tickCount:this.Ud,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Qa].map(c=>({tag:c.bd,index:c.Qd,peak:c.Za,rms:c.Zd,binCount:c.l.frequencyBinCount,freqBins:c.Md}))});0===a.length&&0===this.Qa.size&&this.Vb&&(this.s.Ad(this.de),this.Vb=!1)}static Ge(b){return b*Ya}static od(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Ee(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.nb.Jb(self.fb);"use strict";function wb(b){b.Yb||(b.Yb=b.Cc());return b.Yb}self.kd=class{constructor(b,a,c,d,e){this.u=b;this.kf=a;this.Ja=c;this.T=d;this.ff=e;this.Ic="";this.Yb=null}j(){this.Yb=this.u=null}Cc(){}V(){return this.u.V()}sc(){return this.kf}ib(){return this.Ja}qc(){return this.T}Aa(){return this.ff}fa(){}};"use strict";
self.te=class extends self.kd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.zb=this.Ab=null;this.L.addEventListener("canplaythrough",()=>!0);this.Db=this.V().createGain();this.Cb=null;this.L.addEventListener("canplay",()=>{this.Ab&&(this.Ab(),this.zb=this.Ab=null);!this.Cb&&this.L&&(this.Cb=this.V().createMediaElementSource(this.L),this.Cb.connect(this.Db))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.zb&&(this.zb(f),this.zb=this.Ab=null)})}j(){Bb(this.u,this);this.Db.disconnect();this.Db=null;this.Cb.disconnect();this.Cb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Cc(){return new Promise((b,a)=>{this.Ab=b;this.zb=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Fb(b){if(b.Fa)return b.Fa;var a=b.u.s;if("cordova"===a.A&&a.rd(b.Ja)&&a.Wb)b.Fa=await a.Kb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Gb(b){if(b.ha)return b.ha;b.ha=await Ab(b.u,b.Fa,b.jf);b.Fa=null}
self.ve=class extends self.kd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ha=this.Fa=null;this.jf=!!f}j(){Bb(this.u,this);this.ha=this.Fa=null;super.j()}async Cc(){try{await Fb(this),await Gb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Hb=0;
function Q(b,a){a=!!a;b.wb!==a&&(b.wb=a,b.wb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Xd,b.F.distanceModel=b.u.Hd,b.F.refDistance=b.u.Yd,b.F.maxDistance=b.u.Wd,b.F.rolloffFactor=b.u.$d),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Xb!==a&&(b.Xb=a,b.Xb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function eb(b,a){b.Xb&&b.ad!==a&&(b.ca.pan.value=a,b.ad=a)}function U(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.tc()}function Eb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Qb())}
function db(b,a,c,d,e){if(b.wb){var f=b.Ya,g=b.Xa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Tc?b.u.Mc:performance.now()/1E3}
self.ld=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Rb=Hb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.wb=!1;this.Ya=[0,0,0];this.Xa=[0,0,0];this.ra=[0,0,0];this.ca=null;this.Xb=!1;this.ad=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ka=1;this.ua=!1;this.la=1;b=this.u.dd;this.Tc=1===b&&!this.Aa()||2===b;this.Ua=this.pa=-1;this.be=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return yb(this.u,0<this.na.length?this.na[0]:"")}sc(){return this.P.sc()}ib(){return this.P.ib()}qc(){return this.P.qc()}Aa(){return this.P.Aa()}O(){}oc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}La(){}fa(){return this.P.fa()}Play(){}Ba(){}lb(){}Mb(){}Oa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.be&&this.Ba(),Cb(this.u,"fade-ended",this.na,this.Rb))}tc(){const b=this.Ka;return isFinite(b)?b:0}Lb(){return this.u.Lb()}Qb(){}wc(){}Da(){}vc(){}xc(){}uc(){}hb(){var b=
this.Rb,a=this.na,c=this.fa(),d=-1===this.Ua?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ya,orient:this.Xa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.qc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.uc(),pan:f,stereoPan:this.ca?
this.ad:null}}Dc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Eb(this,b.isMuted)}};"use strict";
self.ue=class extends self.ld{constructor(b,a,c){super(b,a,c);this.P.Db.connect(this.G);this.P.onended=()=>this.Ec()}j(){this.Ba();this.P.Db.disconnect();super.j()}W(){return this.P.W()}Ec(){this.I=!0;this.pa=-1;Cb(this.u,"ended",this.na,this.Rb)}O(){return this.W().ended}oc(){return this.I?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.ib()}' to position '${c}': `,e)}this.u.Ca(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Na(b);this.I=!0;this.J=!1;this.pa=-1}lb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Na(b);this.J=!0}}Mb(){!this.J||this.I||this.O()||(this.u.Ca(this.W()),this.J=!1)}Qb(){this.W().muted=this.ua||this.Lb()}wc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Da(){let b=this.la;this.Tc&&(b*=this.u.kc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}vc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}uc(){return this.La()}xc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.W()),this.sa=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.pb=null}
self.we=class extends self.ld{constructor(b,a,c){super(b,a,c);this.o=null;this.bc=d=>this.Ec(d);this.Nc=!0;this.pb=null;this.S=this.dc=this.fc=0;this.Xc=1}j(){this.Ba();W(this);this.bc=null;super.j()}Ec(b){this.J||this.sa||b.target!==this.pb||(this.I=this.Nc=!0,this.pa=-1,W(this),Cb(this.u,"ended",this.na,this.Rb))}O(){return!this.I&&this.o&&this.o.loop||this.J?!1:this.Nc}oc(){return!this.o||this.I?!0:this.O()}La(){let b;b=this.J?this.S:this.dc+(V(this)-this.fc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Xc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ha;this.o.connect(this.G);this.pb=this.o;this.o.onended=this.bc;this.o.loop=b;this.o.start(d,c);this.J=this.I=this.Nc=!1;this.Y=b;this.la=1;this.fc=V(this);this.dc=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}lb(){this.J||this.I||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.fa()),this.J=!0,this.o.stop(0))}Mb(){!this.J||this.I||this.O()||(W(this),
this.o=this.V().createBufferSource(),this.o.buffer=this.P.ha,this.o.connect(this.G),this.pb=this.o,this.o.onended=this.bc,this.o.loop=this.Y,U(this,this.Ka),this.Da(),this.o.start(0,this.S),this.fc=V(this),this.dc=this.S,this.J=!1)}tc(){return super.tc()*this.Xc}Qb(){this.Xc=this.ua||this.Lb()?0:1;U(this,this.Ka)}wc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Tc&&(b*=this.u.kc);this.o&&(this.o.playbackRate.value=b)}vc(b){this.I||this.O()||(this.J?this.S=b:(this.lb(),
this.S=b,this.Mb()))}uc(){return this.S}xc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.La(),this.Y&&(this.S%=this.fa()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ha,this.o.connect(this.G),this.pb=this.o,this.o.onended=this.bc,this.o.loop=this.Y,U(this,this.Ka),this.Da(),this.o.start(0,this.S),this.fc=V(this),this.dc=this.S,this.sa=!1)}Dc(b){super.Dc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.u=b;this.g=b.V();this.Qd=-1;this.T=this.bd="";this.m=null}j(){this.g=null}N(){}U(){}hb(){return{type:this.T,tag:this.bd,params:this.m}}}
self.me=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Bb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.ub=X(this);this.ub.gain.value=c;this.v.connect(this.Bb);this.v.connect(this.h);this.Bb.connect(this.i);this.Bb.connect(this.X);this.X.connect(this.ub);this.ub.connect(this.Bb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Bb.disconnect();
this.X.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.fb.od;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.ub.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.je=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Gd=this.Fd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=this.g.createConvolver();this.tb.normalize=c;this.tb.buffer=a;this.v.connect(this.tb);this.v.connect(this.h);this.tb.connect(this.i)}j(){this.v.disconnect();this.tb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}hb(){const b=super.hb();b.bufferOriginalUrl=this.Fd;b.bufferUrl="";b.bufferType=this.Gd;return b}};
self.ne=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.vb=X(this);this.vb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.vb);this.vb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.vb.gain,a/100,c,d)}}};
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.oe=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.fb.od;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.re=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.se=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.qe=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Gb=X(this);this.Gb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Gb.gain);this.C.start(0);this.v.connect(this.Gb);this.v.connect(this.h);this.Gb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Gb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.ic=X(this);this.hc=X(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.lc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.lc.curve=this.Jc;this.v.connect(this.ic);this.v.connect(this.h);this.ic.connect(this.lc);this.lc.connect(this.hc);this.hc.connect(this.i)}j(){this.v.disconnect();this.ic.disconnect();this.lc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.ie=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.he=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Md=new Float32Array(this.l.frequencyBinCount);this.ae=new Uint8Array(a);this.Zd=this.Za=0;b=this.u;b.Qa.add(this);T(b)}j(){this.u.Qa.delete(this);this.l.disconnect();super.j()}Oa(){this.l.getFloatFrequencyData(this.Md);this.l.getByteTimeDomainData(this.ae);const b=this.l.fftSize;let a=this.Za=0;for(var c=0;c<b;++c){let d=(this.ae[c]-
128)/128;0>d&&(d=-d);this.Za<d&&(this.Za=d);a+=d*d}c=self.fb.Ee;this.Za=c(this.Za);this.Zd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Ib(b,a){a=a.type;let c=!0;0===a?c=await Jb():1===a&&(c=await Kb());m(b,"permission-result",{type:a,result:c})}
async function Jb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Kb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.nb.Jb(class extends self.gb{constructor(b){super(b,"touch");q(this,"request-permission",a=>Ib(this,a))}});"use strict";function Lb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}
function Mb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Nb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Ob(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}async function Pb(){const b=await Qb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}
async function Rb(b){if(!b.Ia)try{b.Ia=await navigator.wakeLock.request("screen"),b.Ia.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ia=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Sb(b){const a=await Qb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Qb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Lb(b),Mb(b),Nb(b),Ob(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.nb.Jb(class extends self.gb{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>Pb()],["request-wake-lock",()=>Rb(this)],["release-wake-lock",()=>{this.Ia&&(this.Ia.release(),this.Ia=null)}]]);window.addEventListener("resize",()=>Sb(this));this.Ia=null}});
