function k(b,a,c,d){b.o.kb(b.nb,a,c,d)}function l(b,a,c,d){b.o.ca?k(b,a,c,d):b.o.Fe()._OnMessageFromDOM({type:"event",component:b.nb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.o.C(b.nb,a,c)}function n(b,a){for(const [c,d]of a)aa(b,c,d)}function t(b){b.Sb||(b.o.qd(b.Xd),b.Sb=!0)}window.fb=class{constructor(b,a){this.o=b;this.nb=a;this.Sb=!1;this.Xd=()=>this.Na()}gd(){}Na(){}};
window.pf=class{constructor(){this.cd=-1}j(){-1!==this.cd&&(self.clearTimeout(this.cd),this.cd=-1)}};"use strict";class ba{constructor(b){this.Kc=b;this.Nc=!1;this.Uc=!0}}function ca(b,a){const c=a.elementId,d=b.ld(c,a),e=new ba(d);b.qb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Uc=!!a.isVisible;a=b.yc(d);a.addEventListener("focus",()=>{da(b,"elem-focused",c)});a.addEventListener("blur",()=>{da(b,"elem-blurred",c)});b.Ob&&document.body.appendChild(d)}
function ea(b,a){aa(b,"get-element",c=>{const d=u(b,c.elementId);return a(d,c)})}function u(b,a){b=b.qb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Kc}function da(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.qe=class extends self.fb{constructor(b){super(b,"button");this.qb=new Map;this.Ob=!0;n(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=u(this,a);this.Ob&&c.parentElement.removeChild(c);this.qb.delete(a)}],["set-visible",a=>{if(this.Ob){var c=this.qb.get(a.elementId),d=c.Kc;c.Nc?d.style.display=a.isVisible?"":"none":c.Uc=!!a.isVisible}}],["update-position",a=>{if(this.Ob){var c=this.qb.get(a.elementId),d=c.Kc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Nc||(c.Nc=!0,c.Uc&&(d.style.display=""))}}],["update-state",a=>{const c=u(this,a.elementId);this.vc(c,a)}],["focus",a=>this.Ec(a)],["set-css-style",a=>{const c=u(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{u(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{u(this,a.elementId).removeAttribute(a.name)}]]);ea(this,a=>
a)}ld(){throw Error("required override");}vc(){throw Error("required override");}yc(b){return b}Ec(b){const a=this.yc(u(this,b.elementId));b.focus?a.focus():a.blur()}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.df?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.hf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function na(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let y=new Audio;
const oa={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function pa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let A=0;window.RealFile=window.File;const D=[],F=new Map,G=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.wa=class b{constructor(a){this.ca=a.kf;this.ya=null;this.ba="";this.$a=a.gf;this.Eb={};this.Ta=this.ua=null;this.Qb=[];this.I=this.na=null;this.Rc=!1;this.Ed=0;this.tb=null;this.Za=-1;this.$e=()=>this.Ne();this.Ya=[];this.dd=null;this.Yd=[];this.v=a.Zd;this.Tb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&na()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===
this.v&&this.ca)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.va()?self.chrome.webview.addEventListener("message",c=>this.vd(c.data)):"macos-wkwebview"===this.v&&(self.C3WrapperOnMessage=c=>this.vd(c));this.Wb=this.ra=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Je(c));this.C("runtime","create-job-worker",()=>this.Ke());this.C("runtime","send-wrapper-extension-message",c=>this.Qe(c));"cordova"===this.v?document.addEventListener("deviceready",()=>this.td(a)):this.td(a)}j(){this.wc();this.ya&&(this.ya=this.ya.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Ta&&(this.Ta.j(),this.Ta=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}ue(){return fa&&"cordova"===this.v}rc(){const a=
navigator.userAgent;return fa&&ta.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}se(){return v}nd(){return v&&ta.has(this.v)}va(){return"windows-webview2"===this.v||!!("preview"===this.v&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async td(a){"macos-wkwebview"===this.v?this.Ea({type:"ready"}):this.va()&&(this.Te(),this.Yd=(await this.Ie()).registeredComponentIds);if("playable-ad"===this.v){this.ra=self.c3_base64files;this.Wb={};await this.Be();
for(let d=0,e=a.bb.length;d<e;++d){var c=a.bb[d];this.Wb.hasOwnProperty(c)?a.bb[d]={df:!0,hf:this.Wb[c]}:this.ra.hasOwnProperty(c)&&(a.bb[d]=URL.createObjectURL(this.ra[c]))}a.kc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.qd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.ff?this.ba=a.ff:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.mf&&(this.Eb=a.mf);
c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Me(d));this.tb=new self.ve(this);await va(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.He(a,c.port2):
await this.Ge(a,c.port2)}zc(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?this.Eb["workermain.js"]:"playable-ad"===this.v&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async mc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Tb)return a=await this.Fb(d.cf?a:this.$a+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}sd(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.ib(),m=a.tf,p=window.cr_previewImageBlobs||this.ra,q=window.cr_previewProjectFileBlobs,B=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Zd;var r=(new URLSearchParams(self.location.search)).has("debug"),C=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:B,swClientId:x,exportType:a,isDebug:r,ife:!!self.sf,jobScheduler:{inputPort:C.Qc,outputPort:C.Yc,maxNumWorkers:C.Xe},supportedAudioFormats:oa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$a+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.$a+"opus.wasm.wasm",isFileProtocol:this.Tb,isiOSCordova:this.ue(),isiOSWebView:this.rc(),isWebView2Wrapper:this.va(),wrapperComponentIds:this.Yd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async He(a,c){const d=this.zc(a.lf);"preview"===this.v?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.ua.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.ua.addEventListener("message",p);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.mc(d,this.ba,{type:"module",name:"Runtime",cf:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.kc||[],g=a.bb;f=await Promise.all(f.map(h=>this.Oa(h)));g=await Promise.all(g.map(h=>this.Oa(h)));if("cordova"===this.v)for(let h=0,m=a.jc.length;h<
m;++h){const p=a.jc[h],q=p[0];if(q===a.ed||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Oa(q)}this.ua.postMessage(Object.assign(this.sd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.jc,mainProjectScript:a.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...xa(this.tb)]);this.Qb=D.map(h=>new h(this));this.rd();ya(this.na);self.c3_callFunction=(h,m)=>{var p=this.na;return p.o.pd(p.nb,
"js-invoke-function",{name:h,params:m})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.kb("runtime","go-to-last-error-script"))}async Ge(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Qb=D.map(g=>new g(this));this.rd();var d=a.bb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.kc)){var e=[...a.kc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Oa(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;e=a.ed;const f=a.jc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Oa(h),await w(h),"preview"!==this.v||d[g]||this.wd(g,"main script did not run to completion")}catch(m){this.wd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Oa(h),await w(h);"preview"===this.v&&"object"!==typeof self.nf.qf?
(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.sd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:sa}),ya(this.na),this.ud(),this.Ta=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ta,a))}wd(a,c){this.Kb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ud(){this.Kb()}Kb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ke(){const a=await za(this.tb);return{outputPort:a,transferables:[a]}}Fe(){if(this.ca)throw Error("not available in worker mode");return this.Ta}kb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}pd(a,c,d,e,f){const g=ra++,h=new Promise((m,p)=>{G.set(g,{resolve:m,reject:p})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Le(a);if("result"===c)this.Oe(a);else if("runtime-ready"===c)this.Pe();else if("alert-error"===c)this.Kb(),alert(a.message);else if("creating-runtime"===c)this.ud();else throw Error(`unknown message '${c}'`);
}Le(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Jb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Jb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Jb(f,!1,""+h)}):this.Jb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Jb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Oe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}C(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static cb(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}rd(){for(const a of this.Qb)if("runtime"===a.nb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}Me(a){this.kb("debugger","message",a)}Pe(){for(const a of this.Qb)a.gd()}static ib(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ua)}static Lb(a){ua=!!a}qd(a){this.Ya.push(a);this.Gc()}Se(a){a=this.Ya.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ya.splice(a,1);this.Ya.length||this.wc()}Gc(){-1===this.Za&&this.Ya.length&&(this.Za=requestAnimationFrame(this.$e))}wc(){-1!==this.Za&&(cancelAnimationFrame(this.Za),this.Za=-1)}Ne(){this.Za=
-1;for(const a of this.Ya)a();this.Gc()}Da(a){this.na.Da(a)}Ma(a){this.na.Ma(a)}Fc(){this.na.Fc()}Ib(a){this.na.Ib(a)}te(){return!!oa["audio/webm; codecs=opus"]}async Ue(a){a=await this.pd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}xe(a){this.Rc=!0;this.Ed=a}re(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}od(a){return!this.re(a)}async Oa(a){return"cordova"===this.v&&(a.startsWith("file:")||this.Tb&&this.od(a))?(a.startsWith(this.ba)&&
(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Je(a){const c=a.filename;switch(a.as){case "text":return await this.pe(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}kd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async pe(a){a=await this.kd(a);return await pa(a)}xc(){if(z.length&&!(8<=A)){A++;
var a=z.shift();this.Ce(a.filename,a.jf,a.bf)}}Fb(a){return new Promise((c,d)=>{z.push({filename:a,jf:e=>{A--;this.xc();c(e)},bf:e=>{A--;this.xc();d(e)}});this.xc()})}async Ce(a,c,d){try{const e=await this.kd(a),f=await qa(e);c(f)}catch(e){d(e)}}vd(a){if("entered-fullscreen"===a)b.Lb(!0),H(this.na);else if("exited-fullscreen"===a)b.Lb(!1),H(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.dd(a),this.dd=null):"extension-message"===c?this.kb("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Qe(a){this.Ea({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ea(a){this.va()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.v&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Te(){window.moveTo=(a,c)=>{this.Ea({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=
(a,c)=>{this.Ea({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ie(){return this.va()?new Promise(a=>{this.dd=a;this.Ea({type:"wrapper-init"})}):Promise.resolve()}async Be(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Ae(c,d));await Promise.all(a)}async Ae(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Wb[a]=c.str;else{let d=await this.Ee(c);d||(d=this.De(c));this.ra[a]=d}}async Ee(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}De(a){a=this.Re(a);return this.ze(a.data,a.ef)}Re(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{ef:a,data:d}}ze(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.wa;function Aa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};
function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}
function Ga(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ha(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ga(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ia(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ja=new Set(["input","textarea","datalist","select"]),Ka=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ka.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ha(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function ya(b){b.Dd=!0;b.Vc=b.o.pa();b.ub=b.o.ia()}function H(b){if(!b.$){var a=I.ib();a&&"any"!==b.ad&&Na(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Oa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Pa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Qa(b){return await self.C3_GetSvgImageSize(b.blob)}function Ra(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Sa(b){self.setTimeout(()=>{b.Cd=!0},1E3);"cordova"===b.o.v?(document.addEventListener("pause",()=>Ta(b,!0)),document.addEventListener("resume",()=>Ta(b,!1))):document.addEventListener("visibilitychange",()=>Ta(b,"hidden"===document.visibilityState));b.$b=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.$b}}
function Ua(b){b.yd||(b.yd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Va(b){b.xd||(b.xd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Wa(b){await Ea(b.url)}
function Xa(b,a){b.Fd=a.message;-1===b.Lc&&(b.Lc=setTimeout(()=>{b.Lc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Fd)},250))}function Ya(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.ib(),innerWidth:b.pa(),innerHeight:b.ia()})}function Ta(b,a){b.$b!==a&&((b.$b=a)?b.o.wc():b.o.Gc(),k(b,"visibilitychange",{hidden:a}))}
function Za(b,a,c){"Backspace"===c.key&&L(c);if(!b.$){var d=Ba.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function $a(b,a,c,d){b.$||Aa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function ab(b){window!==window.top&&window.focus();bb(b.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.zb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),$a(b,d,c,Ca),b.zb=c.buttons)}}
function cb(b,a,c){if(!b.$&&!Aa(c)){var d=b.zb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.zb=c.buttons;$a(b,c.type,c,Ca)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function db(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function gb(b,a,c,d){const e=b.pa(),f=b.ia();b.ab=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()}):10>d&&hb(b,e,f,d+1)}
function hb(b,a,c,d){-1!==b.ab&&clearTimeout(b.ab);b.ab=setTimeout(()=>gb(b,a,c,d),48)}
function Na(b){b=b.ad;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.cb(class extends self.fb{constructor(b){super(b,"runtime");this.Kd=!0;this.Dd=!1;this.ab=-1;this.ad="any";this.$b=this.xd=this.yd=!1;this.fc=document.createElement("div");this.fc.className="c3-screen-reader-text";this.fc.setAttribute("aria-live","polite");document.body.appendChild(this.fc);this.Ha=null;this.$=!1;this.Fd="";this.Lc=-1;this.Cd=!1;this.Vc=b.pa();this.ub=b.ia();this.da=this.Db=0;b.C("canvas","update-size",d=>{var e=this.o;e.Rc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Kd&&(e.style.display="",this.Kd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Oa(d));b.C("runtime","raster-svg-image",d=>Pa(d));b.C("runtime",
"get-svg-image-size",d=>Qa(d));b.C("runtime","set-target-orientation",d=>{this.ad=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ra(d));b.C("runtime","go-to-script",d=>Ra(d));b.C("runtime","before-start-ticking",()=>Sa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ua(this));b.C("runtime","enable-device-motion",()=>Va(this));b.C("runtime","add-stylesheet",d=>Wa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Cc(d));
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.fc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.o.I.style.display="";this.o.xe(d.duration)});b.C("runtime","export-to-video-progress",d=>Xa(this,d));b.C("runtime","exported-to-video",d=>{window.af({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.af({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ia(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.zb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Dd){var d=this.pa();var e=this.ia();if(this.o.nd()){if(this.Cd){if(this.Vc===
d&&e<this.ub){this.Db=this.ub-e;db(this,this.ub,this.Db);d=void 0;break a}0<this.Db&&(this.Db=0,db(this,e,this.Db))}this.Vc=d;this.ub=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.ib()});this.o.rc()&&(-1!==this.ab&&clearTimeout(this.ab),gb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",d=>Ya(this,d));window.addEventListener("webkitfullscreenerror",d=>Ya(this,d));window.addEventListener("mozfullscreenerror",d=>Ya(this,d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ia(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ua=new Set;this.Yb=new WeakSet;this.xa=!1}gd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},Da);this.zb=0});window.addEventListener("focusin",a=>{a=a.target;(Ja.has(a.tagName.toLowerCase())||Ia(a))&&
k(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>Za(this,"keydown",a));window.addEventListener("keyup",a=>Za(this,"keyup",a));window.addEventListener("dblclick",a=>$a(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{ab(a);M(this,"pointerdown",a)}),this.o.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);cb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>cb(this,
"pointermove",a)),window.addEventListener("mouseup",a=>cb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Fc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.o.se()&&!this.o.nd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.o.pa()}ia(){return this.o.ia()}Fc(){var b=[...this.Ua];this.Ua.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Yb.has(a)||this.Ua.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Yb.delete(b);let a;try{a=b.play()}catch(c){this.Ua.add(b);return}a&&a.catch(()=>{this.Yb.has(b)||this.Ua.add(b)})}Ma(b){this.Ua.delete(b);this.Yb.add(b)}Ib(b){this.xa=!!b}Cc(b){alert(b.message)}});"use strict";
async function va(b){if(b.Ve)throw Error("already initialised");b.Ve=!0;var a=b.za.zc(("playable-ad"===b.za.v?b.za.$a:"")+"dispatchworker.js");b.Jc=await b.za.mc(a,b.mb,{name:"DispatchWorker"});a=new MessageChannel;b.Qc=a.port1;b.Jc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await za(b)}function xa(b){return[b.Qc,b.Yc]}
async function za(b){const a=b.Ld.length;var c=b.za.zc(("playable-ad"===b.za.v?b.za.$a:"")+"jobworker.js");c=await b.za.mc(c,b.mb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Jc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ld.push(c);return e.port1}
self.ve=class{constructor(b){this.za=b;this.mb=b.ba;this.mb="preview"===b.v?this.mb+"workers/":this.mb+b.$a;this.Xe=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Ld=[];this.Yc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.wa({kf:!1,lf:"workermain.js",bb:["scripts/c3runtime.js"],jc:[],ed:"",gf:"scripts/",kc:[],Zd:"html5"}));"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.bc=!0;b.bd=a.timeScaleMode;b.Qd=["equalpower","HRTF","soundfield"][a.panningModel];b.Bd=["linear","inverse","exponential"][a.distanceModel];b.Rd=a.refDistance;b.Pd=a.maxDistance;b.Td=a.rolloffFactor;if(b.o.Rc)b.bc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.o.Ed)});else{var c={latencyHint:a.latencyHint};b.Wd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Qa=b.g.createGain();b.Qa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,B=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Md=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(q){P(b.R,!0);var r=b.R,C=q.innerAngle,la=q.outerAngle,ma=q.outerGain;if(r.sb){ob(r,q.x,q.y,q.z,q.angle);var E=self.eb.ye;r.sa[0]!==E(C)&&
(r.sa[0]=E(C),r.F.coneInnerAngle=E(C));r.sa[1]!==E(la)&&(r.sa[1]=E(la),r.F.coneOuterAngle=E(la));r.sa[2]!==ma&&(r.sa[2]=ma,r.F.coneOuterGain=ma)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof B&&0!==B?(Q(b.R,!0),pb(b.R,B)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,m,p,x)}catch(Cb){console.error("[Construct] Audio: error starting playback: ",Cb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.fd--;0===d.fd&&(d.resolve(),b.Bb.delete(c))}t(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of R(b,c))if(!h.Sa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Ra=g;h.Vd=a}S(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of R(b,c))d.ma!==a&&(d.ma=a,d.Fa())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of R(b,c))d.sc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.ee(b,...e);else if("delay"===c)d=new self.ce(b,...e);else if("convolution"===c){var g=d=new self.be(b,f.ja,...e),h=a.bufferType;g.zd=a.bufferOriginalUrl;g.Ad=h}else if("flanger"===c)d=new self.fe(b,...e);else if("phaser"===
c)d=new self.he(b,...e);else if("gain"===c)d=new self.ge(b,...e);else if("stereopan"===c)d=new self.je(b,...e);else if("tremolo"===c)d=new self.ke(b,...e);else if("ringmod"===c)d=new self.ie(b,...e);else if("distortion"===c)d=new self.de(b,...e);else if("compressor"===c)d=new self.ae(b,...e);else if("analyser"===c)d=new self.$d(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.la.get(h);p||(p=[],g.la.set(h,p));d.Jd=p.length;d.$c=h;p.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.hc=a.timeScale;b.Mc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.xa=a.isSilent;b.o.Ib(b.xa);b.Xb=a.masterVolume;b.Qa.gain.value=
b.Xb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Id?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.o.kb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Db(d)),b.Id=!0);await c}catch(c){Db(c)}}
function kb(b){b.Rb||(b.Pc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Rb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.hb()===c)return await Eb(g),g;if(f)return null;if(e&&(b.bc||b.Hd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.Ba()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Wd;e&&f&&(b.Hd=!0);c=!e||b.bc||f?new self.ne(b,a,c,d,e,f):new self.le(b,a,c,d,e);b.ka.push(c);await Eb(c);b.Od.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Od.add(a));return c}
function Fb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Gb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function xb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Hb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Wc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Hb(b,a){if(a)for(const c of b.H)Fb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ib(b,a,c){return c?b.o.Ue(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Jb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Fb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.hb()===c&&(g.lc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Hc?new self.me(a.u,a,e):new self.oe(a.u,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={fd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.fd++}function rb(b,a){return(b=b.Bb.get((0===a.length?b.Md:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Pa.size)t(b);else for(const a of b.H)if(!a.J&&!a.O()){t(b);break}}function Kb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.Sc||(b.Sc=!0,Promise.resolve().then(()=>Lb(b)))}
function Lb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.gb());k(b,"fxstate",{fxstate:a});b.Sc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(B){console.error("[Construct] Audio: error loading audio state: ",B);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Wa[0]=f[0],b.Wa[1]=f[1],b.Wa[2]=f[2],f=d.orient,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],e.setPosition(...b.Wa),e.setOrientation(...b.Va),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),pb(b,d));c.Play(m,p,q,0);a.isPlaying||c.jb();c.Bc(a)}}}function Db(b){console.error("[Audio] Offline rendering error: ",b)}
self.eb=class extends self.fb{constructor(b){super(b,"audio");this.Qa=this.g=null;this.Rb=this.Pc=!1;this.Aa=()=>{if(!this.Pc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Rb&&(this.Pc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Rb=!1)}};this.ka=[];this.H=[];this.R=null;this.Md=[];this.Od=new Set;this.Nd=-1;this.Bb=new Map;this.Xb=1;this.xa=!1;this.bd=0;this.hc=1;this.Mc=0;this.Qd="HRTF";this.Bd="inverse";this.Rd=600;this.Pd=1E4;this.Td=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Hd=this.bc=!1;this.Wd=this.o.te();this.la=new Map;this.Pa=new Set;this.Id=this.Sc=!1;this.Wc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Wc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Gb(this,this.Wc))};this.Pb=null;self.C3Audio_GetOutputStream=()=>{this.Pb||(this.Pb=this.g.createMediaStreamDestination(),this.Qa.connect(this.Pb));return this.Pb.stream};self.C3Audio_DOMInterface=this;n(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.jb():d.Hb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.Xb=a.vol;this.Qa.gain.value=this.Xb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Mb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.o.Ib(this.xa);for(const c of this.H)c.Mb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.tc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);xb(this,a)}}],["tick",a=>{this.hc=a.timeScale;this.Mc=a.gameTime;this.Nd=a.tickCount;if(0!==this.bd)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Qa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Gb(){return this.xa}Da(b){this.o.Da(b)}Ma(b){this.o.Ma(b)}Na(){for(var b of this.Pa)b.Na();
b=this.g.currentTime;for(var a of this.H)a.Na(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.gb());k(this,"state",{tickCount:this.Nd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Pa].map(c=>({tag:c.$c,index:c.Jd,peak:c.Xa,rms:c.Sd,binCount:c.l.frequencyBinCount,freqBins:c.Gd}))});0===a.length&&0===this.Pa.size&&this.Sb&&(this.o.Se(this.Xd),this.Sb=!1)}static ye(b){return b*ib}static md(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static we(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.wa.cb(self.eb);"use strict";function Eb(b){b.Vb||(b.Vb=b.Ac());return b.Vb}self.hd=class{constructor(b,a,c,d,e){this.u=b;this.Ze=a;this.Ja=c;this.T=d;this.We=e;this.Hc="";this.Vb=null}j(){this.Vb=this.u=null}Ac(){}V(){return this.u.V()}oc(){return this.Ze}hb(){return this.Ja}nc(){return this.T}Ba(){return this.We}ha(){}};"use strict";
self.le=class extends self.hd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Hc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.vb=this.wb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.yb=null;this.M.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.M&&(this.yb=this.V().createMediaElementSource(this.M),this.yb.connect(this.Ab))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Jb(this.u,this);this.Ab.disconnect();this.Ab=null;this.yb.disconnect();this.yb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ac(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.M.src=this.Ja})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Nb(b){if(b.Ga)return b.Ga;var a=b.u.o;if("cordova"===a.v&&a.od(b.Ja)&&a.Tb)b.Ga=await a.Fb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Ob(b){if(b.ja)return b.ja;b.ja=await Ib(b.u,b.Ga,b.Ye);b.Ga=null}
self.ne=class extends self.hd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Hc="webaudio";this.ja=this.Ga=null;this.Ye=!!f}j(){Jb(this.u,this);this.ja=this.Ga=null;super.j()}async Ac(){try{await Nb(this),await Ob(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Pb=0;
function P(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Qd,b.F.distanceModel=b.u.Bd,b.F.refDistance=b.u.Rd,b.F.maxDistance=b.u.Pd,b.F.rolloffFactor=b.u.Td),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function Q(b,a){a=!!a;b.Ub!==a&&(b.Ub=a,b.Ub?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function pb(b,a){b.Ub&&b.Zc!==a&&(b.fa.pan.value=a,b.Zc=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Ra=-1;b.G.gain.value=b.pc()}function Mb(b,a){a=!!a;b.Sa!==a&&(b.Sa=a,b.Mb())}
function ob(b,a,c,d,e){if(b.sb){var f=b.Wa,g=b.Va,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Tc?b.u.Mc:performance.now()/1E3}
self.jd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Nb=Pb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.sb=!1;this.Wa=[0,0,0];this.Va=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Ub=!1;this.Zc=0;this.J=!0;this.Y=this.ta=this.K=!1;this.Ka=1;this.Sa=!1;this.ma=1;b=this.u.bd;this.Tc=1===b&&!this.Ba()||2===b;this.Ra=this.qa=-1;this.Vd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ga(){return Gb(this.u,0<this.oa.length?this.oa[0]:"")}oc(){return this.P.oc()}hb(){return this.P.hb()}nc(){return this.P.nc()}Ba(){return this.P.Ba()}O(){}lc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}La(){}ha(){return this.P.ha()}Play(){}Ca(){}jb(){}Hb(){}Na(b){-1!==this.Ra&&b>=this.Ra&&(this.Ra=-1,this.Vd&&this.Ca(),Kb(this.u,"fade-ended",this.oa,this.Nb))}pc(){const b=this.Ka;return isFinite(b)?b:0}Gb(){return this.u.Gb()}Mb(){}tc(){}Fa(){}sc(){}uc(){}qc(){}gb(){var b=
this.Nb,a=this.oa,c=this.ha(),d=-1===this.Ra?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Wa,orient:this.Va,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.La(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Sa,resumePosition:this.qc(),pan:f,stereoPan:this.fa?
this.Zc:null}}Bc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Fa());Mb(this,b.isMuted)}};"use strict";
self.me=class extends self.jd{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Ca();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Dc(){this.J=!0;this.qa=-1;Kb(this.u,"ended",this.oa,this.Nb)}O(){return this.W().ended}lc(){return this.J?!0:this.O()}La(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.hb()}' to position '${c}': `,e)}this.u.Da(d);this.K=this.J=!1;this.Y=b;this.ma=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Ma(b);this.J=!0;this.K=!1;this.qa=-1}jb(){if(!(this.K||this.J||this.O())){var b=this.W();b.paused||b.pause();this.u.Ma(b);this.K=!0}}Hb(){!this.K||this.J||this.O()||(this.u.Da(this.W()),this.K=!1)}Mb(){this.W().muted=this.Sa||this.Gb()}tc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Fa(){let b=this.ma;this.Tc&&(b*=this.u.hc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.J&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}qc(){return this.La()}uc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Da(this.W()),this.ta=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.lb=null}
self.oe=class extends self.jd{constructor(b,a,c){super(b,a,c);this.s=null;this.Zb=d=>this.Dc(d);this.Oc=!0;this.lb=null;this.S=this.ac=this.cc=0;this.Xc=1}j(){this.Ca();V(this);this.Zb=null;super.j()}Dc(b){this.K||this.ta||b.target!==this.lb||(this.J=this.Oc=!0,this.qa=-1,V(this),Kb(this.u,"ended",this.oa,this.Nb))}O(){return!this.J&&this.s&&this.s.loop||this.K?!1:this.Oc}lc(){return!this.s||this.J?!0:this.O()}La(){let b;b=this.K?this.S:this.ac+(U(this)-this.cc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Xc=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ja;this.s.connect(this.G);this.lb=this.s;this.s.onended=this.Zb;this.s.loop=b;this.s.start(d,c);this.K=this.J=this.Oc=!1;this.Y=b;this.ma=1;this.cc=U(this);this.ac=c}Ca(){if(this.s)try{this.s.stop(0)}catch(b){}this.J=!0;this.K=!1;this.qa=-1}jb(){this.K||this.J||this.O()||(this.S=this.La(),this.Y&&(this.S%=this.ha()),this.K=!0,this.s.stop(0))}Hb(){!this.K||this.J||this.O()||(V(this),this.s=
this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.lb=this.s,this.s.onended=this.Zb,this.s.loop=this.Y,T(this,this.Ka),this.Fa(),this.s.start(0,this.S),this.cc=U(this),this.ac=this.S,this.K=!1)}pc(){return super.pc()*this.Xc}Mb(){this.Xc=this.Sa||this.Gb()?0:1;T(this,this.Ka)}tc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Fa(){let b=this.ma;this.Tc&&(b*=this.u.hc);this.s&&(this.s.playbackRate.value=b)}sc(b){this.J||this.O()||(this.K?this.S=b:(this.jb(),this.S=
b,this.Hb()))}qc(){return this.S}uc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.La(),this.Y&&(this.S%=this.ha()),this.s.stop(0)):this.ta=!1:this.ta&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ja,this.s.connect(this.G),this.lb=this.s,this.s.onended=this.Zb,this.s.loop=this.Y,T(this,this.Ka),this.Fa(),this.s.start(0,this.S),this.cc=U(this),this.ac=this.S,this.ta=!1)}Bc(b){super.Bc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Jd=-1;this.T=this.$c="";this.m=null}j(){this.g=null}N(){}U(){}gb(){return{type:this.T,tag:this.$c,params:this.m}}}
self.ee=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ce=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.xb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.pb=W(this);this.pb.gain.value=c;this.A.connect(this.xb);this.A.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.X);this.X.connect(this.pb);this.pb.connect(this.xb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.X.disconnect();this.pb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.eb.md;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.pb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.be=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Ad=this.zd="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ob=this.g.createConvolver();this.ob.normalize=c;this.ob.buffer=a;this.A.connect(this.ob);this.A.connect(this.h);this.ob.connect(this.i)}j(){this.A.disconnect();this.ob.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}gb(){const b=super.gb();b.bufferOriginalUrl=this.zd;b.bufferUrl="";b.bufferType=this.Ad;return b}};
self.fe=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.rb=W(this);this.rb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.rb);this.rb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.rb.gain,a/100,c,d)}}};
self.he=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.ge=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.eb.md;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.je=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.ke=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ie=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Cb=W(this);this.Cb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Cb.gain);this.B.start(0);this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Cb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.de=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=W(this);this.ec=W(this);this.dc=W(this);b=d;.01>b&&(b=.01);this.ec.gain.value=b;this.dc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.ic.curve=this.Ic;this.A.connect(this.ec);this.A.connect(this.h);this.ec.connect(this.ic);this.ic.connect(this.dc);this.dc.connect(this.i)}j(){this.A.disconnect();this.ec.disconnect();this.ic.disconnect();this.dc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ae=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.$d=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Gd=new Float32Array(this.l.frequencyBinCount);this.Ud=new Uint8Array(a);this.Sd=this.Xa=0;b=this.u;b.Pa.add(this);S(b)}j(){this.u.Pa.delete(this);this.l.disconnect();super.j()}Na(){this.l.getFloatFrequencyData(this.Gd);this.l.getByteTimeDomainData(this.Ud);const b=this.l.fftSize;let a=this.Xa=0;for(var c=0;c<b;++c){let d=(this.Ud[c]-
128)/128;0>d&&(d=-d);this.Xa<d&&(this.Xa=d);a+=d*d}c=self.eb.we;this.Xa=c(this.Xa);this.Sd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";
self.wa.cb(class extends self.fb{constructor(b){super(b,"mouse");n(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.o.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Qb(){}function Rb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Sb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.wa.cb(class extends self.fb{constructor(b){super(b,"browser");this.v="";n(this,[["get-initial-state",a=>{this.v=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Rb(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Sb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.o.va()?window.open(c,"_blank"):this.rf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.o.va()||"macos-wkwebview"===this.v)self.wa.Lb(!0),this.o.Ea({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Qb)}}],["exit-fullscreen",()=>{if(this.o.va()||"macos-wkwebview"===this.v)self.wa.Lb(!1),this.o.Ea({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Qb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",
()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Cc(b){alert(b.message)}Ec(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";function Z(b){b.stopPropagation()}
self.wa.cb(class extends self.qe{constructor(b){super(b)}ld(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",Z);d.addEventListener("pointerrawupdate",
Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;l(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.vc(d,a);return d}yc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}vc(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;
b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});
