function k(b,a,c,d){b.v.gb(b.kb,a,c,d)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.ye()._OnMessageFromDOM({type:"event",component:b.kb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function aa(b,a,c){b.v.C(b.kb,a,c)}function q(b,a){for(const [c,d]of a)aa(b,c,d)}function t(b){b.Pb||(b.v.gd(b.Rd),b.Pb=!0)}window.Cb=class{constructor(b,a){this.v=b;this.kb=a;this.Pb=!1;this.Rd=()=>this.Ka()}Zc(){}Ka(){}};
window.jf=class{constructor(){this.Vc=-1}j(){-1!==this.Vc&&(self.clearTimeout(this.Vc),this.Vc=-1)}};"use strict";function ba(b,a){aa(b,"get-element",c=>{const d=u(b,c.elementId);return a(d,c)})}function u(b,a){b=b.Nb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ud}
window.hf=class extends self.Cb{constructor(b,a){super(b,a);this.Nb=new Map;this.Cc=!0;q(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=u(this,c);this.Cc&&d.parentElement.removeChild(d);this.Nb.delete(c)}],["set-visible",c=>{if(this.Cc){var d=this.Nb.get(c.elementId),e=d.ud;d.Ad?e.style.display=c.isVisible?"":"none":d.Qe=!!c.isVisible}}],["update-position",c=>{if(this.Cc){var d=this.Nb.get(c.elementId),e=d.ud;e.style.left=c.left+"px";e.style.top=c.top+
"px";e.style.width=c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Ad||(d.Ad=!0,d.Qe&&(e.style.display=""))}}],["update-state",c=>{u(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=u(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=u(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{u(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",
c=>{u(this,c.elementId).removeAttribute(c.name)}]]);ba(this,c=>c)}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ea=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ye?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.bf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let y=new Audio;
const ja={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function ma(b){b=await na(b);return(new TextDecoder("utf-8")).decode(b)}
function na(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let oa=0;const pa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");pa.push(b)};const qa=new Set(["cordova","playable-ad","instant-games"]);let ra=!1;
window.Fb=class b{constructor(a){this.ca=a.df;this.wa=null;this.ba="";this.Xa=a.af;this.Ab={};this.Qa=this.ua=null;this.Mb=[];this.I=this.na=null;this.Kc=!1;this.xd=0;this.pb=null;this.Wa=-1;this.Ue=()=>this.Ge();this.Va=[];this.Wc=null;this.Sd=[];this.A=a.Td;this.Qb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ca=!1);this.ca&&da&&(this.ca=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ca=!1;if("cordova"===
this.A&&this.ca)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.eb()?self.chrome.webview.addEventListener("message",c=>this.md(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.md(c));this.Tb=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ce(c));this.C("runtime","create-job-worker",()=>this.De());this.C("runtime","send-wrapper-extension-message",c=>this.Je(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.kd(a)):this.kd(a)}j(){this.tc();this.wa&&(this.wa=this.wa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}ne(){return ca&&"cordova"===this.A}pc(){const a=
navigator.userAgent;return ca&&qa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}le(){return v}dd(){return v&&qa.has(this.A)}eb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async kd(a){"macos-wkwebview"===this.A?this.hb({type:"ready"}):this.eb()&&(this.Me(),this.Sd=(await this.Be()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.Tb={};await this.ue();
for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Tb.hasOwnProperty(c)?a.Za[d]={Ye:!0,bf:this.Tb[c]}:this.ra.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.ra[c]))}a.hc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.gd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.$e?this.ba=a.$e:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.ff&&(this.Ab=a.ff);
c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Fe(d));this.pb=new self.oe(this);await sa(this.pb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ae(a,c.port2):
await this.ze(a,c.port2)}vc(a){a=this.Ab.hasOwnProperty(a)?this.Ab[a]:a.endsWith("/workermain.js")&&this.Ab.hasOwnProperty("workermain.js")?this.Ab["workermain.js"]:"playable-ad"===this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async kc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Qb)return a=await this.Bb(d.Xe?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}pa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}jd(a){var c=this.ba,d=location.href,e=this.pa(),f=this.ia(),g=window.devicePixelRatio,h=b.cb(),m=a.mf,n=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.Td;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.pb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.lf,jobScheduler:{inputPort:B.Jc,outputPort:B.Qc,maxNumWorkers:B.Re},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Qb,isiOSCordova:this.ne(),isiOSWebView:this.pc(),isWebView2Wrapper:this.eb(),wrapperComponentIds:this.Sd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ae(a,c){const d=this.vc(a.ef);"preview"===this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const n=p=>{this.ua.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():m()};this.ua.addEventListener("message",n);this.ua.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.ua=await this.kc(d,this.ba,{type:"module",name:"Runtime",Xe:!0});this.I=document.createElement("canvas");this.I.style.display="none";const e=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.hc||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.A)for(let h=0,m=a.fc.length;h<
m;++h){const n=a.fc[h],p=n[0];if(p===a.Xc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.La(p)}this.ua.postMessage(Object.assign(this.jd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.fc,mainProjectScript:a.Xc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...ta(this.pb)]);this.Mb=E.map(h=>new h(this));this.hd();ua(this.na);self.c3_callFunction=(h,m)=>{var n=this.na;return n.v.fd(n.kb,
"js-invoke-function",{name:h,params:m})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.gb("runtime","go-to-last-error-script"))}async ze(a,c){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Mb=E.map(g=>new g(this));this.hd();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.hc)){var e=[...a.hc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.La(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;e=a.Xc;const f=a.fc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await w(h),"preview"!==this.A||d[g]||this.nd(g,"main script did not run to completion")}catch(m){this.nd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await w(h);"preview"===this.A&&"object"!==typeof self.gf.kf?
(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.jd(a),{isInWorker:!1,messagePort:c,canvas:this.I,runOnStartupFunctions:pa}),ua(this.na),this.ld(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}nd(a,c){this.Ib();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ld(){this.Ib()}Ib(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async De(){const a=await va(this.pb);return{outputPort:a,transferables:[a]}}ye(){if(this.ca)throw Error("not available in worker mode");return this.Qa}gb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}fd(a,c,d,e,f){const g=oa++,h=new Promise((m,n)=>{G.set(g,{resolve:m,reject:n})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ee(a);if("result"===c)this.He(a);else if("runtime-ready"===c)this.Ie();else if("alert-error"===c)this.Ib(),alert(a.message);else if("creating-runtime"===c)this.ld();else throw Error(`unknown message '${c}'`);
}Ee(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Hb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Hb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Hb(f,!1,""+h)}):this.Hb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Hb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}He(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}C(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ic(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}hd(){for(const a of this.Mb)if("runtime"===a.kb){this.na=a;return}throw Error("cannot find runtime DOM handler");
}Fe(a){this.gb("debugger","message",a)}Ie(){for(const a of this.Mb)a.Zc()}static cb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ra)}static od(a){ra=!!a}gd(a){this.Va.push(a);this.Ac()}Le(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.tc()}Ac(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Ue))}tc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Ge(){this.Wa=
-1;for(const a of this.Va)a();this.Ac()}Ba(a){this.na.Ba(a)}Ja(a){this.na.Ja(a)}zc(){this.na.zc()}Gb(a){this.na.Gb(a)}me(){return!!ja["audio/webm; codecs=opus"]}async Ne(a){a=await this.fd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}qe(a){this.Kc=!0;this.xd=a}ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ed(a){return!this.ke(a)}async La(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Qb&&this.ed(a))?(a.startsWith(this.ba)&&
(a=a.substr(this.ba.length)),a=await this.Bb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ce(a){const c=a.filename;switch(a.as){case "text":return await this.je(c);case "buffer":return await this.Bb(c);default:throw Error("unsupported type");}}bd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async je(a){a=await this.bd(a);return await ma(a)}uc(){if(z.length&&!(8<=D)){D++;
var a=z.shift();this.ve(a.filename,a.cf,a.We)}}Bb(a){return new Promise((c,d)=>{z.push({filename:a,cf:e=>{D--;this.uc();c(e)},We:e=>{D--;this.uc();d(e)}});this.uc()})}async ve(a,c,d){try{const e=await this.bd(a),f=await na(e);c(f)}catch(e){d(e)}}md(a){if("entered-fullscreen"===a)b.od(!0),H(this.na);else if("exited-fullscreen"===a)b.od(!1),H(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Wc(a),this.Wc=null):"extension-message"===c?this.gb("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Je(a){this.hb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}hb(a){this.eb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Me(){window.moveTo=(a,c)=>{this.hb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=
(a,c)=>{this.hb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Be(){return this.eb()?new Promise(a=>{this.Wc=a;this.hb({type:"wrapper-init"})}):Promise.resolve()}async ue(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.te(c,d));await Promise.all(a)}async te(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Tb[a]=c.str;else{let d=await this.xe(c);d||(d=this.we(c));this.ra[a]=d}}async xe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}we(a){a=this.Ke(a);return this.se(a.data,a.Ze)}Ke(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ze:a,data:d}}se(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.Fb;function wa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const xa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ya={dispatchUserScriptEvent:!0},K={dispatchRuntimeEvent:!0};
function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}
function Ba(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ca(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await Ba(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Da(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ea=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ca(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function ua(b){b.wd=!0;b.Nc=b.v.pa();b.qb=b.v.ia()}function H(b){if(!b.$){var a=I.cb();a&&"any"!==b.Tc&&Ia(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ia()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.vd=!0},1E3);"cordova"===b.v.A?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.Xb=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.Xb}}
function Pa(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Qa(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Ra(b){await za(b.url)}
function Sa(b,a){b.yd=a.message;-1===b.Fc&&(b.Fc=setTimeout(()=>{b.Fc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.yd)},250))}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.cb(),innerWidth:b.pa(),innerHeight:b.ia()})}function Oa(b,a){b.Xb!==a&&((b.Xb=a)?b.v.tc():b.v.Ac(),k(b,"visibilitychange",{hidden:a}))}
function Ua(b,a,c){"Backspace"===c.key&&M(c);if(!b.$){var d=xa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function Va(b,a,c,d){b.$||wa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function Wa(b){window!==window.top&&window.focus();Xa(b.target)&&document.activeElement&&!Xa(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.vb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Va(b,d,c,ya),b.vb=c.buttons)}}
function Ya(b,a,c){if(!b.$&&!wa(c)){var d=b.vb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.vb=c.buttons;Va(b,c.type,c,ya)}}
function O(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function Za(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function ab(b,a,c,d){const e=b.pa(),f=b.ia();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()}):10>d&&bb(b,e,f,d+1)}
function bb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>ab(b,a,c,d),48)}
function Ia(b){b=b.Tc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Xa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.ic(class extends self.Cb{constructor(b){super(b,"runtime");this.Ed=!0;this.wd=!1;this.Ya=-1;this.Tc="any";this.Xb=this.pd=this.qd=!1;this.cc=document.createElement("div");this.cc.className="c3-screen-reader-text";this.cc.setAttribute("aria-live","polite");document.body.appendChild(this.cc);this.Ea=null;this.$=!1;this.yd="";this.Fc=-1;this.vd=!1;this.Nc=b.pa();this.qb=b.ia();this.da=this.zb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Kc||(e=e.I,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Ed&&(e.style.display="",this.Ed=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ja(d));b.C("runtime","raster-svg-image",d=>Ka(d));b.C("runtime",
"get-svg-image-size",d=>La(d));b.C("runtime","set-target-orientation",d=>{this.Tc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ma(d));b.C("runtime","go-to-script",d=>Ma(d));b.C("runtime","before-start-ticking",()=>Na(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Pa(this));b.C("runtime","enable-device-motion",()=>Qa(this));b.C("runtime","add-stylesheet",d=>Ra(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.cc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.I.style.display="";this.v.qe(d.duration)});b.C("runtime","export-to-video-progress",d=>Sa(this,d));b.C("runtime","exported-to-video",d=>{window.Ve({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ve({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Da(e)||d.preventDefault()});const c=b.I;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);c.addEventListener("selectstart",M);c.addEventListener("gesturehold",
M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),c.addEventListener("pointerdown",M)):c.addEventListener("touchstart",M);this.vb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.wd){var d=this.pa();var e=this.ia();if(this.v.dd()){if(this.vd){if(this.Nc===
d&&e<this.qb){this.zb=this.qb-e;Za(this,this.qb,this.zb);d=void 0;break a}0<this.zb&&(this.zb=0,Za(this,e,this.zb))}this.Nc=d;this.qb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.cb()});this.v.pc()&&(-1!==this.Ya&&clearTimeout(this.Ya),ab(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",d=>Ta(this,d));window.addEventListener("webkitfullscreenerror",d=>Ta(this,d));window.addEventListener("mozfullscreenerror",d=>Ta(this,d));if(b.pc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Da(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ra=new Set;this.Vb=new WeakSet;this.va=!1}Zc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,K)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},K);this.vb=0});window.addEventListener("focusin",a=>{a=a.target;(Ea.has(a.tagName.toLowerCase())||Da(a))&&
k(this,"keyboard-blur",null,K)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>Va(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{Wa(a);N(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Wa(a);Ya(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>Ya(this,
"pointermove",a)),window.addEventListener("mouseup",a=>Ya(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Wa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.zc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.le()&&!this.v.dd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Za(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}pa(){return this.v.pa()}ia(){return this.v.ia()}zc(){var b=[...this.Ra];this.Ra.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.Vb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Vb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Vb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Vb.add(b)}Gb(b){this.va=!!b}});"use strict";async function sa(b){if(b.Oe)throw Error("already initialised");b.Oe=!0;var a=b.xa.vc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"dispatchworker.js");b.Ec=await b.xa.kc(a,b.jb,{name:"DispatchWorker"});a=new MessageChannel;b.Jc=a.port1;b.Ec.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Qc=await va(b)}
function ta(b){return[b.Jc,b.Qc]}async function va(b){const a=b.Fd.length;var c=b.xa.vc(("playable-ad"===b.xa.A?b.xa.Xa:"")+"jobworker.js");c=await b.xa.kc(c,b.jb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Ec.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Fd.push(c);return e.port1}
self.oe=class{constructor(b){this.xa=b;this.jb=b.ba;this.jb="preview"===b.A?this.jb+"workers/":this.jb+b.Xa;this.Re=Math.min(navigator.hardwareConcurrency||2,16);this.Ec=null;this.Fd=[];this.Qc=this.Jc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Fb({df:!0,ef:"workermain.js",Za:["scripts/c3runtime.js"],fc:[],Xc:"",af:"scripts/",hc:[],Td:"html5"}));"use strict";
self.Fb.ic(class extends self.Cb{constructor(b){super(b,"mouse");q(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.v.I.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";const cb=180/Math.PI;
async function db(b,a){if(a.isiOSCordova||a.isSafari)b.Zb=!0;b.Uc=a.timeScaleMode;b.Kd=["equalpower","HRTF","soundfield"][a.panningModel];b.td=["linear","inverse","exponential"][a.distanceModel];b.Ld=a.refDistance;b.Jd=a.maxDistance;b.Nd=a.rolloffFactor;if(b.v.Kc)b.Zb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.xd)});else{var c={latencyHint:a.latencyHint};b.Qd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");eb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&eb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function fb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,n=a.pos,p=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Gd=g.slice(0);gb(b,g);try{b.R=await hb(b,c,d,e,g,f);if(p){Q(b.R,!0);var r=b.R,B=p.innerAngle,ka=p.outerAngle,la=p.outerGain;if(r.ob){ib(r,p.x,p.y,p.z,p.angle);var C=self.$a.re;r.sa[0]!==C(B)&&
(r.sa[0]=C(B),r.F.coneInnerAngle=C(B));r.sa[1]!==C(ka)&&(r.sa[1]=C(ka),r.F.coneOuterAngle=C(ka));r.sa[2]!==la&&(r.sa[2]=la,r.F.coneOuterGain=la)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof A&&0!==A?(R(b.R,!0),jb(b.R,A)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,m,n,x)}catch(vb){console.error("[Construct] Audio: error starting playback: ",vb);return}finally{c=g.join(" ");d=b.xb.get(c);if(!d)throw Error("expected pending tag");d.Yc--;0===d.Yc&&(d.resolve(),b.xb.delete(c))}t(b)}
async function kb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await lb(b,c);for(const h of S(b,c))if(!h.Pa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.s.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ha=d;h.Oa=g;h.Pd=a}T(b)}async function mb(b,a){const c=a.tags;a=a.rate;await lb(b,c);for(const d of S(b,c))d.ma!==a&&(d.ma=a,d.Ca())}async function nb(b,a){const c=a.tags;a=a.pos;await lb(b,c);for(const d of S(b,c))d.qc(a)}
async function ob(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await hb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function pb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function qb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.Zd(b,...e);else if("delay"===c)d=new self.Xd(b,...e);else if("convolution"===c){var g=d=new self.Wd(b,f.ja,...e),h=a.bufferType;g.rd=a.bufferOriginalUrl;g.sd=h}else if("flanger"===c)d=new self.$d(b,...e);else if("phaser"===
c)d=new self.be(b,...e);else if("gain"===c)d=new self.ae(b,...e);else if("stereopan"===c)d=new self.de(b,...e);else if("tremolo"===c)d=new self.ee(b,...e);else if("ringmod"===c)d=new self.ce(b,...e);else if("distortion"===c)d=new self.Yd(b,...e);else if("compressor"===c)d=new self.Vd(b,...e);else if("analyser"===c)d=new self.Ud(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let n=g.la.get(h);n||(n=[],g.la.set(h,n));d.Dd=n.length;d.Sc=h;n.push(d);rb(g,h)}sb(b)}
async function tb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.dc=a.timeScale;b.Gc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.va=a.isSilent;b.v.Gb(b.va);b.Ub=a.masterVolume;b.Na.gain.value=
b.Ub;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>qb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>ub(b,f,c)));T(b)}
async function wb(b,a){try{const c=b.g.suspend(a.time);b.Cd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.gb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>xb(d)),b.Cd=!0);await c}catch(c){xb(c)}}
function eb(b){b.Ob||(b.Ic=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Ob=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ka)if(g.bb()===c)return await yb(g),g;if(f)return null;if(e&&(b.Zb||b.Bd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Qd;e&&f&&(b.Bd=!0);c=!e||b.Zb||f?new self.he(b,a,c,d,e,f):new self.fe(b,a,c,d,e);b.ka.push(c);await yb(c);b.Id.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Id.add(a));return c}
function zb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Ab(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function rb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Bb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Oc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*Bb(b,a){if(a)for(const c of b.H)zb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Db(b,a,c){return c?b.v.Ne(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Eb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(zb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function hb(b,a,c,d,e,f){for(const g of b.H)if(g.bb()===c&&(g.jc()||f))return g.oa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Bc?new self.ge(a.s,a,e):new self.ie(a.s,a,e);b.H.push(e);return e}
function gb(b,a){a=a.join(" ");let c=b.xb.get(a);if(!c){let d=null;c={Yc:0,promise:new Promise(e=>d=e),resolve:d};b.xb.set(a,c)}c.Yc++}function lb(b,a){return(b=b.xb.get((0===a.length?b.Gd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ma.size)t(b);else for(const a of b.H)if(!a.J&&!a.O()){t(b);break}}function Gb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function sb(b){b.Lc||(b.Lc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.ab());k(b,"fxstate",{fxstate:a});b.Lc=!1}
async function ub(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await hb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),jb(b,d));c.Play(m,n,p,0);a.isPlaying||c.fb();c.xc(a)}}}function xb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.Cb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Ob=this.Ic=!1;this.ya=()=>{if(!this.Ic){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ob&&(this.Ic=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Ob=!1)}};this.ka=[];this.H=[];this.R=null;this.Gd=[];this.Id=new Set;this.Hd=-1;this.xb=new Map;this.Ub=1;this.va=!1;this.Uc=0;this.dc=1;this.Gc=0;this.Kd="HRTF";this.td="inverse";this.Ld=600;this.Jd=1E4;this.Nd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Bd=this.Zb=!1;this.Qd=this.v.me();this.la=new Map;this.Ma=new Set;this.Cd=this.Lc=!1;this.Oc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Oc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Ab(this,this.Oc))};this.Lb=null;self.C3Audio_GetOutputStream=()=>{this.Lb||(this.Lb=this.g.createMediaStreamDestination(),this.Na.connect(this.Lb));return this.Lb.stream};self.C3Audio_DOMInterface=this;q(this,[["create-audio-context",a=>db(this,a)],["play",a=>fb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.H)a.Aa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.fb():d.Eb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>kb(this,a)],["set-master-volume",a=>{this.Ub=a.vol;this.Na.gain.value=this.Ub}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ib(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.v.Gb(this.va);for(const c of this.H)c.Jb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.rc(a)}],["set-playback-rate",a=>mb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),jb(d,a)}],["seek",a=>nb(this,a)],["preload",a=>ob(this,a)],["unload",a=>pb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.sc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>qb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);sb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);rb(this,a)}}],["tick",a=>{this.dc=a.timeScale;this.Gc=a.gameTime;this.Hd=a.tickCount;if(0!==this.Uc)for(var c of this.H)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&ib(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>tb(this,a)],["offline-render-audio",a=>wb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Na}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Db(){return this.va}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();
b=this.g.currentTime;for(var a of this.H)a.Ka(b);a=this.H.filter(c=>!c.J&&!c.O()).map(c=>c.ab());k(this,"state",{tickCount:this.Hd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.Sc,index:c.Dd,peak:c.Ua,rms:c.Md,binCount:c.l.frequencyBinCount,freqBins:c.zd}))});0===a.length&&0===this.Ma.size&&this.Pb&&(this.v.Le(this.Rd),this.Pb=!1)}static re(b){return b*cb}static cd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static pe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Fb.ic(self.$a);"use strict";function yb(b){b.Sb||(b.Sb=b.wc());return b.Sb}self.$c=class{constructor(b,a,c,d,e){this.s=b;this.Te=a;this.Ga=c;this.T=d;this.Pe=e;this.Bc="";this.Sb=null}j(){this.Sb=this.s=null}wc(){}V(){return this.s.V()}mc(){return this.Te}bb(){return this.Ga}lc(){return this.T}za(){return this.Pe}ha(){}};"use strict";
self.fe=class extends self.$c{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Bc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.rb=this.sb=null;this.M.addEventListener("canplaythrough",()=>!0);this.wb=this.V().createGain();this.ub=null;this.M.addEventListener("canplay",()=>{this.sb&&(this.sb(),this.rb=this.sb=null);!this.ub&&this.M&&(this.ub=this.V().createMediaElementSource(this.M),this.ub.connect(this.wb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.rb&&(this.rb(f),this.rb=this.sb=null)})}j(){Eb(this.s,this);this.wb.disconnect();this.wb=null;this.ub.disconnect();this.ub=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}wc(){return new Promise((b,a)=>{this.sb=b;this.rb=a;this.M.src=this.Ga})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Jb(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.A&&a.ed(b.Ga)&&a.Qb)b.Da=await a.Bb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Kb(b){if(b.ja)return b.ja;b.ja=await Db(b.s,b.Da,b.Se);b.Da=null}
self.he=class extends self.$c{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Bc="webaudio";this.ja=this.Da=null;this.Se=!!f}j(){Eb(this.s,this);this.ja=this.Da=null;super.j()}async wc(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.ob!==a&&(b.ob=a,b.ob?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Kd,b.F.distanceModel=b.s.td,b.F.refDistance=b.s.Ld,b.F.maxDistance=b.s.Jd,b.F.rolloffFactor=b.s.Nd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function R(b,a){a=!!a;b.Rb!==a&&(b.Rb=a,b.Rb?(Q(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function jb(b,a){b.Rb&&b.Rc!==a&&(b.fa.pan.value=a,b.Rc=a)}function U(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.nc()}function Ib(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Jb())}
function ib(b,a,c,d,e){if(b.ob){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Mc?b.s.Gc:performance.now()/1E3}
self.ad=class{constructor(b,a,c){this.s=b;this.P=a;this.oa=c;this.Kb=Lb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.ob=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.sa=[0,0,0];this.fa=null;this.Rb=!1;this.Rc=0;this.J=!0;this.Y=this.ta=this.K=!1;this.Ha=1;this.Pa=!1;this.ma=1;b=this.s.Uc;this.Mc=1===b&&!this.za()||2===b;this.Oa=this.qa=-1;this.Pd=!1}j(){this.P=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}ga(){return Ab(this.s,0<this.oa.length?this.oa[0]:"")}mc(){return this.P.mc()}bb(){return this.P.bb()}lc(){return this.P.lc()}za(){return this.P.za()}O(){}jc(){}IsPlaying(){return!this.J&&!this.K&&!this.O()}Ia(){}ha(){return this.P.ha()}Play(){}Aa(){}fb(){}Eb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Pd&&this.Aa(),Gb(this.s,"fade-ended",this.oa,this.Kb))}nc(){const b=this.Ha;return isFinite(b)?b:0}Db(){return this.s.Db()}Jb(){}rc(){}Ca(){}qc(){}sc(){}oc(){}ab(){var b=
this.Kb,a=this.oa,c=this.ha(),d=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.mc(),bufferUrl:"",bufferType:this.lc(),isMusic:this.za(),isLooping:this.Y,isMuted:this.Pa,resumePosition:this.oc(),pan:f,stereoPan:this.fa?
this.Rc:null}}xc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Ib(this,b.isMuted)}};"use strict";
self.ge=class extends self.ad{constructor(b,a,c){super(b,a,c);this.P.wb.connect(this.G);this.P.onended=()=>this.yc()}j(){this.Aa();this.P.wb.disconnect();super.j()}W(){return this.P.W()}yc(){this.J=!0;this.qa=-1;Gb(this.s,"ended",this.oa,this.Kb)}O(){return this.W().ended}jc(){return this.J?!0:this.O()}Ia(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.bb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.J=!1;this.Y=b;this.ma=1}Aa(){const b=this.W();b.paused||b.pause();this.s.Ja(b);this.J=!0;this.K=!1;this.qa=-1}fb(){if(!(this.K||this.J||this.O())){var b=this.W();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Eb(){!this.K||this.J||this.O()||(this.s.Ba(this.W()),this.K=!1)}Jb(){this.W().muted=this.Pa||this.Db()}rc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ca(){let b=this.ma;this.Mc&&(b*=this.s.dc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}qc(b){if(!this.J&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}oc(){return this.Ia()}sc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.s.Ba(this.W()),this.ta=!1)}};"use strict";
function W(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.ib=null}
self.ie=class extends self.ad{constructor(b,a,c){super(b,a,c);this.o=null;this.Wb=d=>this.yc(d);this.Hc=!0;this.ib=null;this.S=this.Yb=this.$b=0;this.Pc=1}j(){this.Aa();W(this);this.Wb=null;super.j()}yc(b){this.K||this.ta||b.target!==this.ib||(this.J=this.Hc=!0,this.qa=-1,W(this),Gb(this.s,"ended",this.oa,this.Kb))}O(){return!this.J&&this.o&&this.o.loop||this.K?!1:this.Hc}jc(){return!this.o||this.J?!0:this.O()}Ia(){let b;b=this.K?this.S:this.Yb+(V(this)-this.$b)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Pc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.ib=this.o;this.o.onended=this.Wb;this.o.loop=b;this.o.start(d,c);this.K=this.J=this.Hc=!1;this.Y=b;this.ma=1;this.$b=V(this);this.Yb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.J=!0;this.K=!1;this.qa=-1}fb(){this.K||this.J||this.O()||(this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Eb(){!this.K||this.J||this.O()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Wb,this.o.loop=this.Y,U(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.K=!1)}nc(){return super.nc()*this.Pc}Jb(){this.Pc=this.Pa||this.Db()?0:1;U(this,this.Ha)}rc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Mc&&(b*=this.s.dc);this.o&&(this.o.playbackRate.value=b)}qc(b){this.J||this.O()||(this.K?this.S=b:(this.fb(),this.S=
b,this.Eb()))}oc(){return this.S}sc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Ia(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ta=!1:this.ta&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.ib=this.o,this.o.onended=this.Wb,this.o.loop=this.Y,U(this,this.Ha),this.Ca(),this.o.start(0,this.S),this.$b=V(this),this.Yb=this.S,this.ta=!1)}xc(b){super.xc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Dd=-1;this.T=this.Sc="";this.m=null}j(){this.g=null}N(){}U(){}ab(){return{type:this.T,tag:this.Sc,params:this.m}}}
self.Zd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.tb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.mb=X(this);this.mb.gain.value=c;this.u.connect(this.tb);this.u.connect(this.h);this.tb.connect(this.i);this.tb.connect(this.X);this.X.connect(this.mb);this.mb.connect(this.tb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.tb.disconnect();
this.X.disconnect();this.mb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){const e=self.$a.cd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.mb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.sd=this.rd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.lb=this.g.createConvolver();this.lb.normalize=c;this.lb.buffer=a;this.u.connect(this.lb);this.u.connect(this.h);this.lb.connect(this.i)}j(){this.u.disconnect();this.lb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}ab(){const b=super.ab();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.nb=X(this);this.nb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.u.connect(this.X);this.u.connect(this.h);this.X.connect(this.i);this.X.connect(this.nb);this.nb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.nb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.nb.gain,a/100,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.u.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.ae=class extends Z{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.$a.cd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.de=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ee=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.yb=X(this);this.yb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.yb.gain);this.B.start(0);this.u.connect(this.yb);this.u.connect(this.h);this.yb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.yb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.u=X(this);this.bc=X(this);this.ac=X(this);b=d;.01>b&&(b=.01);this.bc.gain.value=b;this.ac.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.ec=this.g.createWaveShaper();this.Dc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Dc[32768+e]=f,this.Dc[32768-
e-1]=-f;this.ec.curve=this.Dc;this.u.connect(this.bc);this.u.connect(this.h);this.bc.connect(this.ec);this.ec.connect(this.ac);this.ac.connect(this.i)}j(){this.u.disconnect();this.bc.disconnect();this.ec.disconnect();this.ac.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Vd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.Ud=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.zd=new Float32Array(this.l.frequencyBinCount);this.Od=new Uint8Array(a);this.Md=this.Ua=0;b=this.s;b.Ma.add(this);T(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.zd);this.l.getByteTimeDomainData(this.Od);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Od[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.pe;this.Ua=c(this.Ua);this.Md=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
