function k(b,a,c,d){b.i.ba(b.T,a,c,d)}function p(b,a,c,d){b.i.o?k(b,a,c,d):b.i.vb()._OnMessageFromDOM({type:"event",component:b.T,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.i.h(b.T,a,c)}function r(b,a){for(const [c,d]of a)q(b,c,d)}window.aa=class{constructor(b,a){this.i=b;this.T=a}La(){}};window.ac=class{constructor(){}};"use strict";class ba{constructor(b){this.xa=b;this.za=!1;this.Ca=!0}}
function ca(b,a){const c=a.elementId,d=b.na(c,a),e=new ba(d);b.U.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Ca=!!a.isVisible;d.addEventListener("focus",()=>{t(b,"elem-focused",c)});d.addEventListener("blur",()=>{t(b,"elem-blurred",c)});b.fa&&document.body.appendChild(d)}function u(b,a,c){q(b,a,d=>{const e=v(b,d.elementId);return c(e,d)})}function v(b,a){b=b.U.get(a);if(!b)throw Error(`no element with id ${a}`);return b.xa}
function t(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.Na=class extends self.aa{constructor(b,a){super(b,a);this.U=new Map;this.fa=!0;r(this,[["create",c=>ca(this,c)],["destroy",c=>{c=c.elementId;const d=v(this,c);this.fa&&d.parentElement.removeChild(d);this.U.delete(c)}],["set-visible",c=>{if(this.fa){var d=this.U.get(c.elementId),e=d.xa;d.za?e.style.display=c.isVisible?"":"none":d.Ca=!!c.isVisible}}],["update-position",c=>{if(this.fa){var d=this.U.get(c.elementId),e=d.xa;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=c.width+"px";
e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.za||(d.za=!0,d.Ca&&(e.style.display=""))}}],["update-state",c=>{const d=v(this,c.elementId);this.R(d,c)}],["focus",c=>this.ta(c)],["set-css-style",c=>{const d=v(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{v(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{v(this,c.elementId).removeAttribute(c.name)}]]);u(this,"get-element",c=>
c)}na(){throw Error("required override");}R(){throw Error("required override");}ta(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let y=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Rb?new Promise(c=>{const d="c3_resolve_"+y;++y;self[d]=c;a.textContent=b.Vb+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let A=new Audio;
const ia={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.C=class b{constructor(a){this.o=a.Xb;this.X=null;this.m="";this.K=a.Ub;this.$={};this.Ea=this.M=null;this.ga=[];this.j=this.H=null;this.$a=!1;this.V=null;this.J=-1;this.Nb=()=>this.Db();this.Ha=[];this.Ja=null;this.cb=[];this.g=a.eb;this.Ba="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.o=!1);this.o&&da&&(this.o=!1);if("playable-ad"===this.g||"instant-games"===this.g)this.o=!1;if("cordova"===this.g&&this.o)if(x){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.o=!1)}else this.o=!1;this.B()?self.chrome.webview.addEventListener("message",c=>this.Ta(c.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=c=>this.Ta(c));this.ha=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.h("runtime",
"cordova-fetch-local-file",c=>this.zb(c));this.h("runtime","create-job-worker",()=>this.Ab());this.h("runtime","send-wrapper-extension-message",c=>this.Gb(c));"cordova"===this.g?document.addEventListener("deviceready",()=>this.Ra(a)):this.Ra(a)}jb(){return w&&"cordova"===this.g}pa(){const a=navigator.userAgent;return w&&na.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}hb(){return x}Oa(){return x&&na.has(this.g)}B(){return"windows-webview2"===this.g||!!("preview"===this.g&&
window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async Ra(a){"macos-wkwebview"===this.g?this.F({type:"ready"}):this.B()&&(this.Ib(),this.cb=(await this.yb()).registeredComponentIds);if("playable-ad"===this.g){this.A=self.c3_base64files;this.ha={};await this.rb();for(let d=0,e=a.N.length;d<e;++d){var c=a.N[d];this.ha.hasOwnProperty(c)?a.N[d]={Rb:!0,Vb:this.ha[c]}:this.A.hasOwnProperty(c)&&(a.N[d]=URL.createObjectURL(this.A[c]))}a.la=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=
0;this.nb(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Tb?this.m=a.Tb:(c=location.origin,this.m=("null"===c?"file:///":c)+location.pathname,c=this.m.lastIndexOf("/"),-1!==c&&(this.m=this.m.substr(0,c+1)));a.Zb&&(this.$=a.Zb);c=new MessageChannel;this.X=c.port1;this.X.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Cb(d));this.V=new self.kb(this);await pa(this.V);"object"===typeof window.StatusBar&&window.StatusBar.hide();
if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.o?await this.xb(a,c.port2):await this.wb(a,c.port2)}ra(a){a=this.$.hasOwnProperty(a)?this.$[a]:a.endsWith("/workermain.js")&&this.$.hasOwnProperty("workermain.js")?this.$["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oa(a,
c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ba)return a=await this.ma(d.Qb?a:this.K+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}Qa(a){var c=
this.m,d=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.P(),l=a.ec,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,Aa=window.cr_previewProjectFiles,Ba=window.cr_swClientId||"";a=a.eb;var Ca=(new URLSearchParams(self.location.search)).has("debug"),N=this.V;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:n,previewProjectFileSWUrls:Aa,swClientId:Ba,
exportType:a,isDebug:Ca,ife:!!self.dc,jobScheduler:{inputPort:N.Aa,outputPort:N.Ga,maxNumWorkers:N.Lb},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.K+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.K+"opus.wasm.wasm",isFileProtocol:this.Ba,isiOSCordova:this.jb(),isiOSWebView:this.pa(),isWebView2Wrapper:this.B(),wrapperComponentIds:this.cb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xb(a,c){const d=this.ra(a.Yb);"preview"===this.g?
(this.M=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,l)=>{const m=n=>{this.M.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():l()};this.M.addEventListener("message",m);this.M.postMessage({type:"construct-worker-init","import":(new URL(d,this.m)).toString()})})):this.M=await this.oa(d,this.m,{type:"module",name:"Runtime",Qb:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);
window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.la||[],g=a.N;f=await Promise.all(f.map(h=>this.I(h)));g=await Promise.all(g.map(h=>this.I(h)));if("cordova"===this.g)for(let h=0,l=a.ka.length;h<l;++h){const m=a.ka[h],n=m[0];if(n===a.Ka||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.I(n)}this.M.postMessage(Object.assign(this.Qa(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,
projectScripts:a.ka,mainProjectScript:a.Ka,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...qa(this.V)]);this.ga=E.map(h=>new h(this));this.Pa();ra(this.H);self.c3_callFunction=(h,l)=>{var m=this.H;return m.i.lb(m.T,{name:h,params:l})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ba("runtime","go-to-last-error-script"))}async wb(a,c){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&
self.C3_InsertHTMLPlaceholders();this.ga=E.map(g=>new g(this));this.Pa();var d=a.N.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.la)){var e=[...a.la].map(g=>g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.I(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;e=a.Ka;const f=a.ka;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.I(h),await z(h),"preview"!==this.g||d[g]||this.Ua(g,"main script did not run to completion")}catch(l){this.Ua(g,
l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.I(h),await z(h);"preview"===this.g&&"object"!==typeof self.$b.bc?(this.da(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Qa(a),{isInWorker:!1,messagePort:c,canvas:this.j,runOnStartupFunctions:ma}),ra(this.H),
this.Sa(),this.Ea=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ea,a))}Ua(a,c){this.da();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Sa(){this.da()}da(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ab(){const a=await sa(this.V);return{outputPort:a,
transferables:[a]}}vb(){if(this.o)throw Error("not available in worker mode");return this.Ea}ba(a,c,d,e){this.X.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},void 0)}lb(a,c){const d=la++,e=new Promise((f,g)=>{G.set(d,{resolve:f,reject:g})});this.X.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Bb(a);if("result"===
c)this.Eb(a);else if("runtime-ready"===c)this.Fb();else if("alert-error"===c)this.da(),alert(a.message);else if("creating-runtime"===c)this.Sa();else throw Error(`unknown message '${c}'`);}Bb(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.ca(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.ca(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.ca(f,!1,""+h)}):this.ca(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}ca(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.X.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Eb(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}h(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static O(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Pa(){for(const a of this.ga)if("runtime"===a.T){this.H=a;return}throw Error("cannot find runtime DOM handler");}Cb(a){this.ba("debugger","message",a)}Fb(){for(const a of this.ga)a.La()}static P(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static ea(a){oa=!!a}nb(a){this.Ha.push(a);this.va()}va(){-1===this.J&&this.Ha.length&&(this.J=requestAnimationFrame(this.Nb))}pb(){-1!==
this.J&&(cancelAnimationFrame(this.J),this.J=-1)}Db(){this.J=-1;for(const a of this.Ha)a();this.va()}ua(){this.H.ua()}mb(){this.$a=!0}gb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ib(a){return!this.gb(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Ba&&this.ib(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ma(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async zb(a){const c=a.filename;
switch(a.as){case "text":return await this.fb(c);case "buffer":return await this.ma(c);default:throw Error("unsupported type");}}Ma(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async fb(a){a=await this.Ma(a);return await ja(a)}qa(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.sb(a.filename,a.Wb,a.Pb)}}ma(a){return new Promise((c,d)=>{B.push({filename:a,Wb:e=>{D--;this.qa();c(e)},Pb:e=>{D--;this.qa();
d(e)}});this.qa()})}async sb(a,c,d){try{const e=await this.Ma(a),f=await ka(e);c(f)}catch(e){d(e)}}Ta(a){if("entered-fullscreen"===a)b.ea(!0),H(this.H);else if("exited-fullscreen"===a)b.ea(!1),H(this.H);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.Ja(a),this.Ja=null):"extension-message"===c?this.ba("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Gb(a){this.F({type:"extension-message",
componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}F(a){this.B()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ib(){window.moveTo=(a,c)=>{this.F({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.F({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}yb(){return this.B()?new Promise(a=>
{this.Ja=a;this.F({type:"wrapper-init"})}):Promise.resolve()}async rb(){const a=[];for(const [c,d]of Object.entries(this.A))a.push(this.qb(c,d));await Promise.all(a)}async qb(a,c){if("object"===typeof c)this.A[a]=new Blob([c.str],{type:c.type}),this.ha[a]=c.str;else{let d=await this.ub(c);d||(d=this.tb(c));this.A[a]=d}}async ub(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}tb(a){a=this.Hb(a);return this.ob(a.data,a.Sb)}Hb(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Sb:a,data:d}}ob(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,l;for(l=h=0;h<e;++h)g[h]=a.charCodeAt(l++)|a.charCodeAt(l++)<<8|a.charCodeAt(l++)<<16|a.charCodeAt(l++)<<24;for(d&=
3;d--;)f[l]=a.charCodeAt(l),++l;return new Blob([f],{type:c})}};"use strict";const I=self.C;function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},K={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function L(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function M(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function O(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let P=!1;document.addEventListener("pause",()=>P=!0);document.addEventListener("resume",()=>P=!1);function ra(b){b.Ya=!0;b.Da=b.i.v();b.W=b.i.u()}function H(b){if(!b.l){var a=I.P();a&&"any"!==b.Ia&&Ga(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}async function Ha(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ia(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ja(b){return await self.C3_GetSvgImageSize(b.blob)}function Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function La(b){self.setTimeout(()=>{b.Xa=!0},1E3);"cordova"===b.i.g?(document.addEventListener("pause",()=>Q(b,!0)),document.addEventListener("resume",()=>Q(b,!1))):document.addEventListener("visibilitychange",()=>Q(b,"hidden"===document.visibilityState));b.ia=!("hidden"!==document.visibilityState&&!P);return{isSuspended:b.ia}}
function Ma(b){b.Wa||(b.Wa=!0,window.addEventListener("deviceorientation",a=>{b.l||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Oa(b){b.Va||(b.Va=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Pa(b){await wa(b.url)}
function Qa(b,a){b.Za=a.message;-1===b.ya&&(b.ya=setTimeout(()=>{b.ya=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Za)},250))}function R(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.P(),innerWidth:b.v(),innerHeight:b.u()})}function Q(b,a){b.ia!==a&&((b.ia=a)?b.i.pb():b.i.va(),k(b,"visibilitychange",{hidden:a}))}
function Ra(b,a,c){"Backspace"===c.key&&O(c);if(!b.l){var d=ua.get(c.code)||c.code;p(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function S(b,a,c,d){b.l||ta(c)||p(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function T(b){window!==window.top&&window.focus();Sa(b.target)&&document.activeElement&&!Sa(document.activeElement)&&document.activeElement.blur()}
function U(b,a,c){if(!b.l){var d=0;"mouse"===c.pointerType&&(d=b.Y);p(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d="mousemove",
"pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),S(b,d,c,va),b.Y=c.buttons)}}
function V(b,a,c){if(!b.l&&!ta(c)){var d=b.Y;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.s,pageX:c.pageX,pageY:c.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.Y=c.buttons;S(b,c.type,c,va)}}
function W(b,a,c){if(!b.l)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function X(b,a,c){document.body.style.transform="";b.s=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Ta(b,a,c,d){const e=b.v(),f=b.u();b.L=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.P()}):10>d&&Ua(b,e,f,d+1)}
function Ua(b,a,c,d){-1!==b.L&&clearTimeout(b.L);b.L=setTimeout(()=>Ta(b,a,c,d),48)}
function Ga(b){b=b.Ia;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Sa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.O(class extends self.aa{constructor(b){super(b,"runtime");this.ab=!0;this.Ya=!1;this.L=-1;this.Ia="any";this.ia=this.Va=this.Wa=!1;this.ja=document.createElement("div");this.ja.className="c3-screen-reader-text";this.ja.setAttribute("aria-live","polite");document.body.appendChild(this.ja);this.G=null;this.l=!1;this.Za="";this.ya=-1;this.Xa=!1;this.Da=b.v();this.W=b.u();this.s=this.Z=0;b.h("canvas","update-size",d=>{var e=this.i;e.$a||(e=e.j,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.ab&&(e.style.display="",this.ab=!1))});b.h("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.h("runtime","load-webfonts",d=>Ha(d));b.h("runtime","raster-svg-image",d=>Ia(d));b.h("runtime","get-svg-image-size",
d=>Ja(d));b.h("runtime","set-target-orientation",d=>{this.Ia=d.targetOrientation});b.h("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.h("runtime","post-to-debugger",d=>Ka(d));b.h("runtime","go-to-script",d=>Ka(d));b.h("runtime","before-start-ticking",()=>La(this));b.h("runtime","debug-highlight",d=>{if(d.show){this.G||(this.G=document.createElement("div"),this.G.id="inspectOutline",document.body.appendChild(this.G));var e=this.G;e.style.display="";e.style.left=d.left-
1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.G&&(this.G.style.display="none")});b.h("runtime","enable-device-orientation",()=>Ma(this));b.h("runtime","enable-device-motion",()=>Oa(this));b.h("runtime","add-stylesheet",d=>Pa(d));b.h("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.h("runtime","alert",d=>this.sa(d));b.h("runtime","screen-reader-text",
d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.ja.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});b.h("runtime","hide-cordova-splash",
()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.h("runtime","set-exporting-to-video",d=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.mb()});b.h("runtime","export-to-video-progress",d=>Qa(this,d));b.h("runtime","exported-to-video",d=>{window.Ob({type:"exported-video",arrayBuffer:d.arrayBuffer,contentType:d.contentType,
time:d.time})});b.h("runtime","exported-to-image-sequence",d=>{window.Ob({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||M(e)||d.preventDefault()});const c=b.j;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);c.addEventListener("selectstart",O);c.addEventListener("gesturehold",O);window.addEventListener("touchstart",
O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),c.addEventListener("pointerdown",O)):c.addEventListener("touchstart",O);this.Y=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Ya){var d=this.v();var e=this.u();if(this.i.Oa()){if(this.Xa){if(this.Da===d&&e<
this.W){this.Z=this.W-e;X(this,this.W,this.Z);d=void 0;break a}0<this.Z&&(this.Z=0,X(this,e,this.Z))}this.Da=d;this.W=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.P()});this.i.pa()&&(-1!==this.L&&clearTimeout(this.L),Ta(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>H(this));window.addEventListener("fullscreenerror",
d=>R(this,d));window.addEventListener("webkitfullscreenerror",d=>R(this,d));window.addEventListener("mozfullscreenerror",d=>R(this,d));if(b.pa())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):M(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Fa=new Set;this.Mb=new WeakSet;this.Kb=!1}La(){window.addEventListener("focus",()=>{k(this,"window-focus",null,K)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},K);this.Y=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||M(a))&&
k(this,"keyboard-blur",null,K)});window.addEventListener("keydown",a=>Ra(this,"keydown",a));window.addEventListener("keyup",a=>Ra(this,"keyup",a));window.addEventListener("dblclick",a=>S(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.l||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{T(a);U(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a)),window.addEventListener("pointerup",a=>U(this,"pointerup",a)),window.addEventListener("pointercancel",a=>U(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{T(a);V(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>V(this,"pointermove",
a)),window.addEventListener("mouseup",a=>V(this,"pointerup",a)),window.addEventListener("touchstart",a=>{T(a);W(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>W(this,"pointermove",a)),window.addEventListener("touchend",a=>W(this,"pointerup",a)),window.addEventListener("touchcancel",a=>W(this,"pointercancel",a)));const b=()=>this.ua();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.hb()&&!this.i.Oa()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{X(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}ua(){var b=[...this.Fa];this.Fa.clear();if(!this.Kb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Mb.has(a)||this.Fa.add(a)})}sa(b){alert(b.message)}});"use strict";
async function pa(b){if(b.Jb)throw Error("already initialised");b.Jb=!0;var a=b.D.ra(("playable-ad"===b.D.g?b.D.K:"")+"dispatchworker.js");b.wa=await b.D.oa(a,b.S,{name:"DispatchWorker"});a=new MessageChannel;b.Aa=a.port1;b.wa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Ga=await sa(b)}function qa(b){return[b.Aa,b.Ga]}
async function sa(b){const a=b.bb.length;var c=b.D.ra(("playable-ad"===b.D.g?b.D.K:"")+"jobworker.js");c=await b.D.oa(c,b.S,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.wa.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.bb.push(c);return e.port1}
self.kb=class{constructor(b){this.D=b;this.S=b.m;this.S="preview"===b.g?this.S+"workers/":this.S+b.K;this.Lb=Math.min(navigator.hardwareConcurrency||2,16);this.wa=null;this.bb=[];this.Ga=this.Aa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.C({Xb:!0,Yb:"workermain.js",N:["scripts/c3runtime.js"],ka:[],Ka:"",Ub:"scripts/",la:[],eb:"html5"}));"use strict";function Y(b){b.stopPropagation()}
self.C.O(class extends self.Na{constructor(b){super(b,"file-chooser");u(this,"click",a=>{a.click()});u(this,"clear",a=>{a.value=""})}na(b,a){const c=document.createElement("input");c.type="file";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Y);c.addEventListener("pointermove",Y);c.addEventListener("pointerrawupdate",Y);c.addEventListener("pointerup",Y);c.addEventListener("mousedown",Y);c.addEventListener("mouseup",Y);c.addEventListener("change",
()=>t(this,"change",b,{files:Array.from(c.files)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.R(c,a);return c}R(b,a){b.setAttribute("accept",a.accept);a.isMultiSelect?b.setAttribute("multiple",""):b.removeAttribute("multiple")}});"use strict";function Z(b){b.stopPropagation()}
self.C.O(class extends self.Na{constructor(b){super(b,"sliderbar")}na(b,a){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);c.addEventListener("click",
()=>{var d;d||(d={});d.elementId=b;p(this,"click",d)});c.addEventListener("change",()=>t(this,"change",b,{value:parseFloat(c.value)}));c.addEventListener("input",()=>t(this,"input",b,{value:parseFloat(c.value)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.R(c,a);return c}R(b,a){b.max=a.max;b.min=a.min;b.step=a.step;b.value=a.value;b.disabled=!a.isEnabled;b.title=a.title}});"use strict";
self.C.O(class extends self.aa{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.i.j.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Va(){}function Wa(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Xa(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.C.O(class extends self.aa{constructor(b){super(b,"browser");this.g="";r(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Wa(this)],["alert",a=>this.sa(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.ta(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Xa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.i.B()?window.open(c,"_blank"):this.cc||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.i.B()||"macos-wkwebview"===this.g)self.C.ea(!0),this.i.F({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&
(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Va)}}],["exit-fullscreen",()=>{if(this.i.B()||"macos-wkwebview"===this.g)self.C.ea(!1),this.i.F({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Va)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}]]);window.addEventListener("online",
()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}sa(b){alert(b.message)}ta(b){b=b.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
