function m(c,a,b,d){c.h.la(c.Z,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Lb()._OnMessageFromDOM({type:"event",component:c.Z,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function aa(c,a,b){c.h.i(c.Z,a,b)}function t(c,a){for(const [b,d]of a)aa(c,b,d)}window.ja=class{constructor(c,a){this.h=c;this.Z=a}ua(){}};window.uc=class{constructor(){}};"use strict";class ba{constructor(c){this.$=c;this.Ja=!1;this.Ma=!0;this.aa=this.B=this.Va=-1}}
function ca(c,a){const b=a.elementId,d=c.ia(b,a),e=new ba(d);c.J.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ma=!!a.isVisible;var f=c.Aa(d);f.addEventListener("focus",()=>{u(c,"elem-focused",b)});f.addEventListener("blur",()=>{u(c,"elem-blurred",b)});f=a.htmlIndex;e.Va=f;e.aa=a.htmlZIndex;c.N&&(a=c.h.xa(f),e.B=a,c.h.ka(a).appendChild(d))}function w(c,a,b){aa(c,a,d=>{const e=x(c,d.elementId);return b(e,d)})}
function x(c,a){c=c.J.get(a);if(!c)throw Error(`no element with id ${a}`);return c.$}function u(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function y(c,a,b,d){d||(d={});d.elementId=b;r(c,a,d)}
window.V=class extends self.ja{constructor(c,a){super(c,a);this.J=new Map;this.N=!0;t(this,[["create",b=>ca(this,b)],["destroy",b=>{b=b.elementId;const d=x(this,b);this.N&&d.parentElement.removeChild(d);this.J.delete(b)}],["set-visible",b=>{if(this.N){var d=this.J.get(b.elementId),e=d.$;d.Ja?e.style.display=b.isVisible?"":"none":d.Ma=!!b.isVisible}}],["update-position",b=>{if(this.N){var d=this.J.get(b.elementId),e=d.$,f=this.h;e.style.left=b.left+"px";e.style.top=b.top+"px";e.style.width=b.width+
"px";e.style.height=b.height+"px";var h=b.fontSize;null!==h&&(e.style.fontSize=h+"em");h=b.htmlIndex;d.Va=h;h=f.xa(h);h!==d.B&&(e.remove(),f.ka(h).appendChild(e),d.B=h,f.Ga());b=b.htmlZIndex;b!==d.aa&&(d.aa=b,f.Ga());d.Ja||(d.Ja=!0,d.Ma&&(e.style.display=""))}}],["update-state",b=>{const d=x(this,b.elementId);this.G(d,b)}],["focus",b=>this.Da(b)],["set-css-style",b=>{const d=x(this,b.elementId),e=b.prop;b=b.val;e.startsWith("--")?d.style.setProperty(e,b):d.style[e]=b}],["set-attribute",b=>{x(this,
b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{x(this,b.elementId).removeAttribute(b.name)}]]);w(this,"get-element",b=>b)}ia(){throw Error("required override");}G(){throw Error("required override");}Aa(c){return c}Da(c){const a=this.Aa(x(this,c.elementId));c.focus?a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),z=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);
let fa=0;function A(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.kc?new Promise(b=>{const d="c3_resolve_"+fa;++fa;self[d]=b;a.textContent=c.oc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let B=new Audio;
const ia={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function ka(c){c=await la(c);return(new TextDecoder("utf-8")).decode(c)}
function la(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ma=0;const na=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");na.push(c)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.v=class c{constructor(a){this.m=a.qc;this.da=null;this.l="";this.R=a.nc;this.ga={};this.Oa=this.T=null;this.O=[];this.K=null;this.qb=!0;this.j=[];this.Sa=[];this.Ta=!1;this.sb=()=>this.Jb();this.pb=!1;this.ba=null;this.P=-1;this.fc=()=>this.Ub();this.ea=new Set;this.Wa=null;this.tb=[];this.g=a.ub;this.La="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;ea&&(this.m=!1);if("cordova"===this.g&&this.m&&z){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.u()?self.chrome.webview.addEventListener("message",b=>this.ib(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.ib(b));this.pa=this.C=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Yb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Pb());this.i("runtime","cordova-fetch-local-file",b=>this.Qb(b));this.i("runtime","create-job-worker",()=>this.Rb());this.i("runtime","send-wrapper-extension-message",b=>this.Xb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.gb(a)):this.gb(a)}wb(){return this.j[0].canvas}xa(a){return Math.min(a,this.j.length-1)}ka(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ha}Ab(){return da&&
"cordova"===this.g}X(){const a=navigator.userAgent;return da&&oa.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}yb(){return z}Za(){return z&&oa.has(this.g)}$a(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}u(){return this.$a()||"xbox-uwp-webview2"===this.g}async gb(a){this.m&&!await ha()&&(this.m=!1);"macos-wkwebview"===this.g?this.H({type:"ready"}):this.u()&&(this.ac(),this.tb=(await this.Ob()).registeredComponentIds);
if("playable-ad"===this.g){this.C=self.c3_base64files;this.pa={};await this.Gb();for(let d=0,e=a.U.length;d<e;++d){var b=a.U[d];this.pa.hasOwnProperty(b)?a.U[d]={kc:!0,oc:this.pa[b]}:this.C.hasOwnProperty(b)&&(a.U[d]=URL.createObjectURL(this.C[b]))}a.ta=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.ab(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.mc?this.l=a.mc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.sc&&(this.ga=a.sc);b=new MessageChannel;this.da=b.port1;this.da.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Tb(d));this.ba=new self.Bb(this);await qa(this.ba);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Nb(a,b.port2):await this.Mb(a,b.port2)}Ba(a){a=this.ga.hasOwnProperty(a)?this.ga[a]:a.endsWith("/workermain.js")&&this.ga.hasOwnProperty("workermain.js")?this.ga["workermain.js"]:"playable-ad"===this.g&&this.C.hasOwnProperty(a)?this.C[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async wa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.La)return a=await this.va(d.jc?a:this.R+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}A(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}ya(){return this.u()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}fb(a){var b=this.l,d=location.href,e=this.A(),f=this.o(),h=this.ya(),g=window.devicePixelRatio,k=c.W(),l=a.yc,n=window.cr_previewImageBlobs||this.C,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,Ia=window.cr_swClientId||"";a=a.ub;var Ja=(new URLSearchParams(self.location.search)).has("debug"),R=this.ba;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:Ia,exportType:a,isDebug:Ja,ife:!!self.xc,jobScheduler:{inputPort:R.Ka,outputPort:R.Ra,maxNumWorkers:R.dc},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.R+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.R+"opus.wasm.wasm",isFileProtocol:this.La,isiOSCordova:this.Ab(),isiOSWebView:this.X(),
isWindowsWebView2:this.$a(),isAnyWebView2Wrapper:this.u(),wrapperComponentIds:this.tb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Nb(a,b){const d=this.Ba(a.rc);"preview"===this.g?(this.T=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.T.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.T.addEventListener("message",p);this.T.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.T=await this.wa(d,this.l,{type:"module",name:"Runtime",jc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ha:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.ta||[],k=a.U;g=await Promise.all(g.map(l=>this.M(l)));k=await Promise.all(k.map(l=>this.M(l)));
if("cordova"===this.g)for(let l=0,n=a.sa.length;l<n;++l){const p=a.sa[l],q=p[0];if(q===a.Xa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.M(q)}this.T.postMessage(Object.assign(this.fb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.sa,mainProjectScript:a.Xa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...ra(this.ba)]);this.O=E.map(l=>new l(this));this.eb();H(e);I(h);sa(this.K);self.c3_callFunction=
(l,n)=>{var p=this.K;return p.h.Cb(p.Z,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.la("runtime","go-to-last-error-script"))}async Mb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ha:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.O=E.map(g=>new g(this));this.eb();
H(d);I(e);e=a.U.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.ta)){var f=[...a.ta].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.M(g)));await Promise.all(e.map(g=>A(g)));e=self.C3_ProjectScriptsStatus;f=a.Xa;const h=a.sa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.M(k),await A(k),"preview"!==this.g||e[g]||this.jb(g,"main script did not run to completion")}catch(l){this.jb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.M(k),await A(k);"preview"===this.g&&"object"!==typeof self.tc.vc?(this.na(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.fb(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:na}),sa(this.K),this.hb(),this.Oa=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Oa,a))}jb(a,b){this.na();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}hb(){this.na()}na(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Rb(){const a=await ta(this.ba);return{outputPort:a,transferables:[a]}}Yb(a){if(!this.pb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ha:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.qb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.qb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ha:n}=this.j.pop();n.remove();this.m&&!d?this.Sa.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,H(b),I(d),this.j.push({canvas:b,ha:d});for(const l of this.O)if(l instanceof window.V&&l.N)for(const n of l.J.values())e=l.h.xa(n.Va),f=n.B,-1!==e&&-1!==f&&e!==f&&(f=n.$,f.remove(),l.h.ka(e).appendChild(f),n.B=e);this.Ga();return{addedCanvases:a,transferables:k}}Pb(){for(const a of this.Sa)a.remove();this.Sa.length=0}Ga(){this.Ta||(this.Ta=!0,this.ab(this.sb))}Jb(){this.$b(this.sb);
this.Ta=!1;let a=[];for(var b of this.O)if(b instanceof window.V){var d=b.N?[...b.J.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.B,l=g.B;return k!==l?k-l:h.aa-g.aa});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.B!==b&&(this.cb(b,a.slice(d,e)),b=h.B,d=e)}d<e&&this.cb(b,a.slice(d,e))}cb(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.$);var d=new Set(b);a=this.ka(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);
for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Lb(){if(this.m)throw Error("not available in worker mode");return this.Oa}la(a,b,d,e){this.da.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Cb(a,b){const d=ma++,e=new Promise((f,h)=>{G.set(d,{resolve:f,reject:h})});this.da.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=
a.type;if("event"===b)return this.Sb(a);if("result"===b)this.Vb(a);else if("runtime-ready"===b)this.Wb();else if("alert-error"===b)this.na(),alert(a.message);else if("creating-runtime"===b)this.hb();else throw Error(`unknown message '${b}'`);}Sb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ma(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ma(f,
!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ma(f,!1,""+g)}):this.ma(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ma(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.da.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Vb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=G.get(b);d?e.resolve(a):e.reject(a);G.delete(b)}i(a,b,d){let e=F.get(a);e||(e=new Map,
F.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static L(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}eb(){for(const a of this.O)if("runtime"===a.Z){this.K=a;return}throw Error("cannot find runtime DOM handler");}Tb(a){this.la("debugger","message",a)}Wb(){for(const a of this.O)a.ua()}static W(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static oa(a){pa=!!a}ab(a){this.ea.add(a);
this.Fa()}$b(a){this.ea.delete(a);0===this.ea.size&&this.bb()}Fa(){-1===this.P&&0<this.ea.size&&(this.P=requestAnimationFrame(this.fc))}bb(){-1!==this.P&&(cancelAnimationFrame(this.P),this.P=-1)}Ub(){this.P=-1;for(const a of this.ea)a();this.Fa()}Ea(){this.K.Ea()}Db(){this.pb=!0}xb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}zb(a){return!this.xb(a)}async M(a){return"cordova"===this.g&&(a.startsWith("file:")||this.La&&this.zb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.va(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Qb(a){const b=a.filename;switch(a.as){case "text":return await this.vb(b);case "buffer":return await this.va(b);default:throw Error("unsupported type");}}Ya(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async vb(a){a=await this.Ya(a);return await ka(a)}za(){if(C.length&&!(8<=D)){D++;
var a=C.shift();this.Hb(a.filename,a.pc,a.ic)}}va(a){return new Promise((b,d)=>{C.push({filename:a,pc:e=>{D--;this.za();b(e)},ic:e=>{D--;this.za();d(e)}});this.za()})}async Hb(a,b,d){try{const e=await this.Ya(a),f=await la(e);b(f)}catch(e){d(e)}}ib(a){if("entered-fullscreen"===a)c.oa(!0),J(this.K);else if("exited-fullscreen"===a)c.oa(!1),J(this.K);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Wa(a),this.Wa=null):"extension-message"===b?this.la("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Xb(a){this.H({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}H(a){this.u()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ac(){window.moveTo=(a,b)=>{this.H({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=
(a,b)=>{this.H({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Ob(){return this.u()?new Promise(a=>{this.Wa=a;this.H({type:"wrapper-init"})}):Promise.resolve()}async Gb(){const a=[];for(const [b,d]of Object.entries(this.C))a.push(this.Fb(b,d));await Promise.all(a)}async Fb(a,b){if("object"===typeof b)this.C[a]=new Blob([b.str],{type:b.type}),this.pa[a]=b.str;else{let d=await this.Kb(b);d||(d=this.Ib(b));this.C[a]=d}}async Kb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Ib(a){a=this.Zb(a);return this.Eb(a.data,a.lc)}Zb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{lc:a,data:d}}Eb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const K=self.v,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),L={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},M={dispatchUserScriptEvent:!0},N={dispatchRuntimeEvent:!0};function va(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function wa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function xa(c){c=URL.createObjectURL(c);try{return await wa(c)}finally{URL.revokeObjectURL(c)}}function ya(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const za=new Set(["input","textarea","datalist","select"]),Aa=new Set(["canvas","body","html"]);
function O(c){c.target.tagName&&Aa.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function P(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Ba(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await xa(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await xa(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let Q=!1;document.addEventListener("pause",()=>Q=!0);document.addEventListener("resume",()=>Q=!1);function H(c){c.addEventListener("selectstart",O);c.addEventListener("gesturehold",O);c.addEventListener("pointerdown",O)}function I(c){c.addEventListener("selectstart",P);c.addEventListener("gesturehold",P);c.addEventListener("touchstart",P)}function sa(c){c.nb=!0;c.Na=c.h.A();c.ca=c.h.o()}
function J(c){if(!c.s){var a=K.W();a&&"any"!==c.Ua&&Ca(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.A(),innerHeight:c.o()})}}async function Da(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ea(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Fa(c){return await self.C3_GetSvgImageSize(c.blob)}function Ga(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ha(c){self.setTimeout(()=>{c.mb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>S(c,!0)),document.addEventListener("resume",()=>S(c,!1))):document.addEventListener("visibilitychange",()=>S(c,"hidden"===document.visibilityState));c.qa=!("hidden"!==document.visibilityState&&!Q);return{isSuspended:c.qa}}
function Ka(c){c.lb||(c.lb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},L)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},L)}))}
function La(c){c.kb||(c.kb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},L)}}))}async function Ma(c){await va(c.url)}
function Na(c,a){c.ob=a.message;-1===c.Ia&&(c.Ia=setTimeout(()=>{c.Ia=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.ob)},250))}function Oa(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:K.W(),innerWidth:c.A(),innerHeight:c.o()})}
function S(c,a){c.qa!==a&&((c.qa=a)?c.h.bb():c.h.Fa(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.X()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}function Pa(c,a,b){"Backspace"===b.key&&O(b);if(!c.s){var d=ua.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},L)}}
function T(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function U(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Qa);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},L);"mouse"===b.pointerType&&(c.Qa=
b.buttons)}}function Qa(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.F=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.F=a))}}
function Ra(c,a,b,d){const e=c.A(),f=c.o();c.S=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.W(),cssDisplayMode:c.h.ya()}):10>d&&Sa(c,e,f,d+1)}function Sa(c,a,b,d){-1!==c.S&&clearTimeout(c.S);c.S=setTimeout(()=>Ra(c,a,b,d),48)}
function Ca(c){c=c.Ua;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ta(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
K.L(class extends self.ja{constructor(c){super(c,"runtime");this.nb=!1;this.S=-1;this.Ua="any";this.qa=this.kb=this.lb=!1;this.ra=document.createElement("div");this.ra.className="c3-screen-reader-text";this.ra.setAttribute("aria-live","polite");document.body.appendChild(this.ra);this.I=null;this.s=!1;this.ob="";this.Ia=-1;this.mb=!1;this.Na=c.A();this.ca=c.o();this.F=this.fa=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Da(b));c.i("runtime","raster-svg-image",b=>Ea(b));c.i("runtime","get-svg-image-size",b=>Fa(b));c.i("runtime","set-target-orientation",b=>{this.Ua=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ga(b));c.i("runtime","go-to-script",b=>Ga(b));c.i("runtime","before-start-ticking",()=>Ha(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.I||(this.I=document.createElement("div"),this.I.id="inspectOutline",document.body.appendChild(this.I));var d=this.I;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.I&&(this.I.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ka(this));c.i("runtime","enable-device-motion",()=>La(this));c.i("runtime","add-stylesheet",b=>Ma(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.Ca(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.ra.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.wb().style.display=
"";this.h.Db()});c.i("runtime","export-to-video-progress",b=>Na(this,b));c.i("runtime","exported-to-video",b=>{window.hc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.hc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||ya(d)||b.preventDefault()});
window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});window.addEventListener("pointerdown",O,{passive:!1});this.Qa=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Ba,{passive:!1});window.addEventListener("wheel",Ba,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.nb){var b=this.A();var d=this.o();if(this.h.Za()){if(this.mb){if(this.Na===
b&&d<this.ca){this.fa=this.ca-d;Qa(this,this.ca,this.fa);b=void 0;break a}0<this.fa&&(this.fa=0,Qa(this,d,this.fa))}this.Na=b;this.ca=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:K.W(),cssDisplayMode:this.h.ya()});this.h.X()&&(-1!==this.S&&clearTimeout(this.S),Ra(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>J(this));window.addEventListener("webkitfullscreenchange",()=>J(this));window.addEventListener("mozfullscreenchange",
()=>J(this));window.addEventListener("fullscreenerror",b=>Oa(this,b));window.addEventListener("webkitfullscreenerror",b=>Oa(this,b));window.addEventListener("mozfullscreenerror",b=>Oa(this,b));if(c.X()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Pa=new Set;this.ec=new WeakSet;this.cc=!1}ua(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,N)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",{parentHasFocus:a},N);this.Qa=0});window.addEventListener("focusin",a=>{a=a.target;(za.has(a.tagName.toLowerCase())||ya(a))&&m(this,"keyboard-blur",null,N)});window.addEventListener("keydown",a=>Pa(this,"keydown",a));window.addEventListener("keyup",a=>Pa(this,"keyup",a));window.addEventListener("mousedown",a=>T(this,"mousedown",a,M));
window.addEventListener("mousemove",a=>T(this,"mousemove",a,M));window.addEventListener("mouseup",a=>T(this,"mouseup",a,M));window.addEventListener("dblclick",a=>T(this,"dblclick",a,L));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.F,pageX:a.pageX,pageY:a.pageY+this.F,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},L)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ta(a.target)&&
document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur();U(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{U(this,"pointermove",a)}):window.addEventListener("pointermove",a=>U(this,"pointermove",a));window.addEventListener("pointerup",a=>U(this,"pointerup",a));window.addEventListener("pointercancel",a=>U(this,"pointercancel",a));const c=()=>this.Ea();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.yb()&&!this.h.Za()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Qa(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.X()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}A(){return this.h.A()}o(){return this.h.o()}Ea(){var c=
[...this.Pa];this.Pa.clear();if(!this.cc)for(const a of c)(c=a.play())&&c.catch(()=>{this.ec.has(a)||this.Pa.add(a)})}Ca(c){alert(c.message)}});"use strict";async function qa(c){if(c.bc)throw Error("already initialised");c.bc=!0;var a=c.D.Ba(("playable-ad"===c.D.g?c.D.R:"")+"dispatchworker.js");c.Ha=await c.D.wa(a,c.Y,{name:"DispatchWorker"});a=new MessageChannel;c.Ka=a.port1;c.Ha.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ra=await ta(c)}function ra(c){return[c.Ka,c.Ra]}
async function ta(c){const a=c.rb.length;var b=c.D.Ba(("playable-ad"===c.D.g?c.D.R:"")+"jobworker.js");b=await c.D.wa(b,c.Y,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Ha.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.rb.push(b);return e.port1}
self.Bb=class{constructor(c){this.D=c;this.Y=c.l;this.Y="preview"===c.g?this.Y+"workers/":this.Y+c.R;this.dc=Math.min(navigator.hardwareConcurrency||2,16);this.Ha=null;this.rb=[];this.Ra=this.Ka=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.v({qc:!0,rc:"workermain.js",U:["scripts/c3runtime.js"],sa:[],Xa:"",nc:"scripts/",ta:[],ub:"html5"}));"use strict";function W(c){c.stopPropagation()}function Ua(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.v.L(class extends self.V{constructor(c){super(c,"text-input");w(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}ia(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",W);b.addEventListener("pointermove",W);b.addEventListener("pointerrawupdate",W);b.addEventListener("pointerup",W);b.addEventListener("mousedown",
W);b.addEventListener("mouseup",W);b.addEventListener("keydown",Ua);b.addEventListener("keyup",Ua);b.addEventListener("click",e=>{e.stopPropagation();y(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();y(this,"dblclick",c)});b.addEventListener("input",()=>u(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.G(b,a);return b}G(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;
c.spellcheck=a.spellCheck;a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});"use strict";function X(c){c.stopPropagation()}function Va(c){const a=document.createElement("option");a.text=c;return a}function Wa(c){const a=c.selectedIndex,b=[];for(let d=0,e=c.length;d<e;++d)c.options[d].selected&&b.push(d);return{selectedIndex:a,selectedIndices:b}}
self.v.L(class extends self.V{constructor(c){super(c,"list");w(this,"set-selected-index",(a,b)=>{a.selectedIndex=b.selectedIndex});w(this,"add-item",(a,b)=>{const d=b.index;b=Va(b.text);0>d?a.add(b):a.add(b,d)});w(this,"remove-item",(a,b)=>{a.remove(b.index)});w(this,"set-item",(a,b)=>{a.options[b.index].text=b.text});w(this,"clear",a=>{a.innerHTML=""});w(this,"load-state",(a,b)=>{a.innerHTML="";for(const d of b.items)a.add(Va(d));a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=
a.options[d])b.selected=!0})}ia(c,a){const b=a.isDropdown,d=a.isMultiSelect,e=a.items,f=document.createElement("select");f.style.position="absolute";f.style.userSelect="none";f.style.webkitUserSelect="none";f.multiple=d;b||(f.size=2);for(const h of e)f.add(Va(h));f.addEventListener("pointerdown",X);f.addEventListener("pointermove",X);f.addEventListener("pointerrawupdate",X);f.addEventListener("pointerup",X);f.addEventListener("mousedown",X);f.addEventListener("mouseup",X);f.addEventListener("click",
h=>{h.stopPropagation();y(this,"click",c,Wa(f))});f.addEventListener("dblclick",h=>{h.stopPropagation();y(this,"dblclick",c,Wa(f))});f.addEventListener("change",()=>u(this,"change",c,Wa(f)));a.id&&(f.id=a.id);a.className&&(f.className=a.className);this.G(f,a);return f}G(c,a){c.title=a.title;c.disabled=!a.isEnabled;c.multiple=!!a.isMultiSelect}});"use strict";let Y=null,Xa=null;window.addEventListener("beforeinstallprompt",c=>{c.preventDefault();Y=c;Xa&&m(Xa,"install-available");return!1});
function Ya(){}function Za(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function $a(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}async function ab(){if(!Y)return{result:"unavailable"};try{return Y.prompt(),{result:(await Y.userChoice).outcome}}catch(c){return console.error("[Construct] Requesting install failed: ",c),{result:"failed"}}}
self.v.L(class extends self.ja{constructor(c){super(c,"browser");this.g="";t(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Za(this)],["alert",a=>this.Ca(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Da(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>$a(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,
"_system"):"preview"===a||this.h.u()?window.open(b,"_blank"):this.wc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.u()||"macos-wkwebview"===this.g)self.v.oa(!0),this.h.H({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&
(b.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Ya)}}],["exit-fullscreen",()=>{if(this.h.u()||"macos-wkwebview"===this.g)self.v.oa(!1),this.h.H({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Ya)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=
document.querySelector(e);f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}],["request-install",()=>ab()]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}ua(){Y?m(this,"install-available"):Xa=this;window.addEventListener("appinstalled",
()=>{m(this,"app-installed")})}Ca(c){alert(c.message)}Da(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;c?a.focus():a.blur()}else c?window.focus():window.blur()}});"use strict";function Z(c){c.stopPropagation()}
self.v.L(class extends self.V{constructor(c){super(c,"button")}ia(c,a){const b=document.createElement("input");var d=b;a.isCheckbox?(b.type="checkbox",d=document.createElement("label"),d.appendChild(b),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):b.type="button";d.style.position="absolute";d.addEventListener("pointerdown",Z);d.addEventListener("pointermove",
Z);d.addEventListener("pointerrawupdate",Z);d.addEventListener("pointerup",Z);d.addEventListener("mousedown",Z);d.addEventListener("mouseup",Z);d.addEventListener("keydown",Z);d.addEventListener("keyup",Z);d.addEventListener("contextmenu",e=>e.preventDefault());b.addEventListener("click",()=>y(this,"click",c,{isChecked:b.checked}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.G(d,a);return d}Aa(c){return"input"===c.tagName.toLowerCase()?c:c.firstChild}G(c,a){const b="input"===c.tagName.toLowerCase()?
c:c.firstChild;b.checked=a.isChecked;b.disabled=!a.isEnabled;c.title=a.title;c===b?b.value=a.text:c.lastChild.textContent=a.text}});"use strict";function bb(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=()=>a(d.result);d.onerror=()=>b(d.error);d.readAsArrayBuffer(c)})}async function cb(c,a){a=a.text;let b=!1;try{await navigator.clipboard.writeText(a),b=!0}catch(d){console.error("Failed to copy to clipboard: ",d),b=!1}m(c,"copy-result",{isOk:b})}
async function db(c,a){const b=a.arrayBuffer;a=a.type;let d=!1;try{const e={};e[a]=new Blob([b],{type:a});await navigator.clipboard.write([new ClipboardItem(e)]);d=!0}catch(e){console.error("Failed to copy to clipboard: ",e),d=!1}m(c,"copy-result",{isOk:d})}async function eb(c){let a=!1,b="";try{b=await navigator.clipboard.readText(),a=!0}catch(d){console.error("Failed to paste: ",d),b="",a=!1}m(c,"request-paste-text-result",{isOk:a,text:b})}
async function fb(c){let a=!1,b=[];try{var d=await navigator.clipboard.read();if(1<=d.length){const e=d[0];d=[];const f=e.types;for(const h of f)d.push((async()=>{const g=await e.getType(h);return await bb(g)})());b=(await Promise.all(d)).map((h,g)=>[f[g],h]);a=!0}else a=!1}catch(e){console.error("Failed to paste: ",e),a=!1}m(c,"request-paste-binary-result",{isOk:a,binary:b})}
async function gb(c,a){if((new Set(["canvas","body","html"])).has((a.target.tagName||"").toLowerCase())){a.preventDefault();var b=a.clipboardData.getData("text");b?m(c,"window-paste-text",{text:b}):1<=a.clipboardData.files.length&&(a=a.clipboardData.files[0],b=await bb(a),m(c,"window-paste-binary",{arrayBuffer:b,type:a.type}))}}
self.v.L(class extends self.ja{constructor(c){super(c,"clipboard");t(this,[["copy-text",a=>cb(this,a)],["copy-binary",a=>db(this,a)],["request-paste-text",()=>eb(this)],["request-paste-binary",()=>fb(this)]]);window.addEventListener("paste",a=>gb(this,a))}});
